python-attrs/attrs

- attr/_make.py
- tests/test_dark_magic.py
Currently, if you subclass an `@attr.s`-decorated class without re-decorating with another `@attr.s`, the `repr` displays the name of the superclass, not the subclass.
> Fix the repr to work for non-redecorated subclass.

- AUTHORS.rst
- attr/_make.py
- docs/changelog.rst
> ENH: query attributes through private API to speed up validate.

- CHANGELOG.rst
- docs/examples.rst
- src/attr/_make.py
- tests/test_dunders.py
This allows for clean initializer parameter lists while being able to
initialize attributes to default values.
> Allow the case of initializing attributes that are set to `init=False`

- src/attr/_compat.py
- src/attr/_make.py
- src/attr/filters.py
Importing `attrs` on my fairly decent machine takes around 20-30 ms. Since I am using `attrs` in CLI tools, every small bit counts, and I'd like to make `import attrs` faster.
`inspect` is known as an expensive module to import, and since we use it only for one trivial oneline method, would it be acceptable to remove `inspect` import ? That makes importing `attrs` more or less free on my machine.
> ENH: bundle inspect.isclass to avoid paying the cost of inspect import.

- .travis.yml
- conftest.py
- src/attr/_funcs.py
- tests/__init__.py
- tests/test_funcs.py
- tox.ini
So yeah, I made a dumb mistake when adding support for `dict_factory` - I forgot to ensure the factory propagates further than the initial class - to attributes containing dicts, lists and other instances of `attrs` classes. It came up instantly at work when we upgraded to actually use the feature :) My bad.
I'm pretty sure the `dict_factory` argument should propagate - one of the use cases is to use an OrderedDict to preserve order, and that's just not going to happen if ordinary dicts are used anywhere in the conversion.
The fix is simple, just propagate the argument in `asdict`.
Since the original tests didn't catch this, I've worked on expanding our Hypothesis strategies. (More challenging than just the fix :) In addition to the `simple_classes` strategy, there is also now a …
> asdict - propagate dict_factory properly

- CHANGELOG.rst
- src/attr/_funcs.py
- tests/test_funcs.py
So, as you might have noticed, I'm totally a fan of this library :) Also, we've been using it at work a lot lately, and it's really working out for us. So I thought I might see if anything can be optimized a little.
We use `asdict` a lot. I actually totally love the way attrs interacts with data contained in Python primitives, like dicts and lists. At a later date I might submit some converters that make these transformations really easy. However, now I was taking a look at `asdict` performance, to see if it can be optimized.
Actually my first instinct was to see if I can use Cython to speed things up, mostly because I wanted to learn Cython a little more. The changes I'm submitting now have a far greater effect than using Cython though, so I'm not sure Cython's worth it. Maybe later? …
> Simplify asdict and has.

- docs/conf.py
This patch allows for [reproducible builds of attrs](https://bugs.debian.org/833886).
An alternative to all this skullduggery is to make the copyright year a static "2015". According to my understanding of the Berne Convention et al, the "first year of publication" is what you should list, so I think that would be fine?
> Make copyright reproducible.

- CHANGELOG.rst
- src/attr/_funcs.py
- src/attr/_make.py
- tests/test_make.py
If this looks good to you, I'll add something to the changelog. Since the docs already define Attributes are read-only, this should be backwards compatible.
> Make Attribute instances immutable and slotted.

- CODE_OF_CONDUCT.rst
- CONTRIBUTING.rst
- README.rst
- docs/api.rst
- docs/backward-compatibility.rst
- docs/examples.rst
- docs/why.rst
Thanks for making this library, and for explicitly requesting typo-fixing PRs.
I heard about it from https://lwn.net/Articles/697146
If you'd prefer, I can squash these commits into one; the only reason they are separate is due to GitHub's in-browser editor.
> Doc typo fixes

- src/attr/_make.py
A little markup typo I found when reading / building the docs.
> Fix little sphinx doc typo

- CHANGELOG.rst
- docs/api.rst
- docs/examples.rst
- src/attr/__init__.py
- src/attr/_make.py
- src/attr/exceptions.py
- tests/test_dark_magic.py
- tests/test_dunders.py
First shot at immutability to fix #3 and #50.
I would very much like some input from y’all that asked for it:  @glyph @radix @Tinche 
A couple of notes:
- I didn’t go for a separate decorator because that would be confusing and harder to implement.
- I called it `frozen` because most Pythonista have heard of `frozenset`.  `immutable` is a bit long, `value` seems confusingly generic and only understandable to people with FP/theory background.
- Originally I wanted to just set `__setattr__` at the end of `__init__` but that doesn’t seem to work unfortunately.  So `object.setattr` it is.
***
I’m not set on any of those decisions and will happily be converted to any other way.  Just please keep in mind, that the feature has to be discoverable and understandable to people who just started …
> [RFC] Implement immutability

- src/attr/_make.py
- tests/test_make.py
- tests/utils.py
OK, here's an idea for an optimization, since we're into that stuff now :)
Assume the attrs class `attr.make_class('C', {'x': attr.ib(validator=validators.instance_of(int)), 'y': attr.ib(), 'z': attr.ib()})`.
The master will generate an __init__ like this:
```
def __init__(self, x, y, z):
self.x = x
self.y = y
self.z = z
validate(self)
```
so I was thinking how to improve this. Ideas in sequence:
1. `validate()` calls `fields()`. Can we avoid the function call by using the `__attrs_attrs__` directly? `validate()` is a public facing API, so alas, no.
2. OK, so what if we don't even call `validate()`, and so avoid that call too? Just put the internal validation code in the generated `__init__`.
3. Now that the code is here, speed things up more by generating smart `__init__` validation …
> Optimize init validators.

- src/attr/_make.py
- tests/test_funcs.py
- tests/test_make.py
- tests/utils.py
Hello, it's me again.
This speeds up Attribute instantiation. 
Before:
```
> pyperf timeit --rigorous -g -s "from attr import Attribute, NOTHING" "Attribute(name='test', default=NOTHING, validator=None, repr=True, cmp=True, hash=True, init=True)"
........................................
5.58 us:  2 #########
5.63 us:  6 ############################
5.68 us:  5 #######################
5.72 us:  9 ##########################################
5.77 us: 11 ###################################################
5.81 us: 17 ###############################################################################
5.86 us:  7 #################################
5.91 us: 10 ##############################################
5.95 us: 15 ######################################################################
6.00 us: 13 …
```
> Speed up Attribute instantiation.

- README.rst
- docs/api.rst
- docs/overview.rst
Also expand the example class a little bit to stress that we're not just
about data containers.
This is kind of a response to questions and concerns that come up in issues – and places that shall not be named –  frequently.
I’d some love feedback from people who *understand* `attrs` and what it stands for.   Ideally also from people who have better words than I.
I really just want to link there and drop the mike in the future.
cc  @hawkowl @glyph @cyli @econchick @Tinche @cournape @mithrandi
> Add a philosophy section

- src/attr/__init__.py
The generated docstring merely points to the docs elsewhere.  I started with "{} <{}>".format, but I'm new to attrs and wasn't sure if that meets the requirement for all supported Python versions.
> add attr docstring

- src/attr/_compat.py
- src/attr/_make.py
The `eval` builtin does exactly this already, with the same signature even.
> remove unnecessary and ugly `exec_` compat hack

- src/attr/_make.py
namedtuple does this and so should we. My bad for forgetting it the first time 'round.
> The ClassAttributes tuple is now slotted.

- setup.cfg
Without this small setup.cfg addition a built wheel does not contain your LICENSE file.
With this, the license file will be added to a built wheel metadata.
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
> Ensure the LICENSE file is included in wheel metadata

- CHANGELOG.rst
- docs/api.rst
- docs/examples.rst
- docs/extending.rst
- src/attr/_compat.py
- src/attr/_make.py
- tests/test_dark_magic.py
- tests/test_dunders.py
- tests/test_funcs.py
- tests/test_make.py
- tests/utils.py
Alright, here's a first pass, open for comments. Docs will come after the implementation is settled.
The syntax is:
```
@attr.s
class A:
a = attr.ib(metadata=<metadata>)
```
where `<metadata>` can be:
- None
- a mapping (technically something that can be passed to the dict constructor)
On Python 2, the metadata (if not None) will be exposed as a plain dict. On Python 3, the original, passed-in mapping will be wrapped in a https://docs.python.org/3.5/library/types.html#types.MappingProxyType.
I'm not entirely happy with None as the default here (it's my pet peeve to have Optional[Collection] instead of just an empty collection) but I feel an empty dict per attribute might be too much memory overhead? MappingProxyType would have solved this elegantly (we would have one empty instance, used …
> Introduce attribute metadata.

- docs/how-does-it-work.rst
Since function calls are discrete one has "fewer" of them.
> docs: "less [...] calls" -> "fewer [...] calls"

- CHANGELOG.rst
- src/attr/_make.py
- tests/test_dark_magic.py
Raise FrozenInstanceError when trying to delete an attribute from
a frozen class.
On non-frozen classes `del` results in un-shadowing the `attr.ib` object which is a bit surprising.
> ENH: forbid delete attr from frozen class

- dev-requirements.txt
- src/attr/_make.py
- tests/test_dark_magic.py
> Preserve metaclass when slots=True

- docs/why.rst
Hi,
Just a minor addition to the docs. This was why I opted for attrs vs namedtuples.
Damian
> Document another reason why not namedtuples

- CHANGELOG.rst
- docs/api.rst
- docs/examples.rst
- src/attr/_make.py
- src/attr/exceptions.py
- tests/test_dark_magic.py
- tests/test_make.py
- tests/utils.py
Now this is a biggie but I believe it’s worth it for 17.1.  There should be no performance penalty but it’s a feature that people have been yearning for since day one. :)
Let me know what you think, contains some boy scouting.  Most notably the completely hosted markup in api.rst around evolve.   Also WTF was with local dunder variables in methods?  I suppose copy pasta?
This enables the following:
```python
@attr.s
class C:
x = attr.ib(default=1)
y = attr.ib(default=attr.Factory(lambda self: self.x + 1, takes_self=True))
z = attr.ib()
@z.default
def whatever(self):
return self.y + 1
```
Now calling `C()` gives you `C(x=1, y=2, z=3)`.
Fixes #165
> Add takes_self to Factory and @_CountingAttr.default

- CHANGELOG.rst
- src/attr/_make.py
- src/attr/validators.py
- tests/test_dark_magic.py
- tests/test_validators.py
- tests/utils.py
This just restores `__hash__` to our validators. I'd have preferred to make them frozen, but that requires a discussion and is maybe better left until we have zero-overhead frozen classes.
See #192.
> Compatibility fixes.

- docs/examples.rst
This adds a paragraph to the documentation that includes the method
described by @Tinche in #174 for making a slot class weak-referenceable.
> Document weakref to slot class

- CHANGELOG.rst
- src/attr/_make.py
- tests/test_dunders.py
Previously:
```pycon
>>> import attr
>>> @attr.s(str=True, slots=True)
... class A(object):
...     a = attr.ib()
...
>>> a = A(1)
>>> str(a)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: unbound method repr_() must be called with A instance as first argument (got nothing instead)
```
Fixes #198.
> Fix unbound __str__ on Python 2 when slots=True

- setup.cfg
- setup.py
- tests/test_funcs.py
pytest 3.1.0 activated all warnings and 3.1.1 deactivated them again.  I’ve found some latent bugs in my own software so I want them to be always on.  I had to add a few context managers to assoc but that’s worth it.
> Activate warnings

- docs/examples.rst
The error message on line 311 said "y must be... when it was supposed to be "x must be...
> Fix typo in example error message

- src/attr/_funcs.py
- src/attr/_make.py
- src/attr/validators.py
Found by scrolling through the files in PyCharm and looking at
highlighted words.
- [N/A] Added **tests** for changed code.
- [N/A] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/utils.py).
- [N/A] Updated **documentation** for changed code.
- [N/A] Documentation in `.rst` files is written using [semantic newlines](http://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [N/A] Changed/added classes/methods/functions have appropriate `versionadded`, …
> Fix some typos in doc strings

- docs/examples.rst
- docs/how-does-it-work.rst
- docs/overview.rst
- tests/test_dark_magic.py
I went with the American spelling of "fulfill" instead of the British "fulfil".
- [N/A] Added **tests** for changed code.
- [N/A] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/utils.py).
- [N/A] Updated **documentation** for changed code.
- [N/A] Documentation in `.rst` files is written using [semantic newlines](http://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [N/A] Changed/added classes/methods/functions have appropriate `versionadded`, …
> Some more typos

- src/attr/_funcs.py
- tests/test_funcs.py
Fixes #208.
I (deliberately) didn't document this change or write a test for it, let me know if that was a mistake.
> Pass appropriate stacklevel in assoc deprecation warning.

- CONTRIBUTING.rst
GitHub sends out mails on new PR pushes since some time already.
If this is still there intentionally, feel free to reject this though!
> Remove review feedback line from CONTRIBUTING

- changelog.d/221.change.rst
- src/attr/_make.py
- tests/test_dark_magic.py
Simply filter out all attributes from super classes that are present in the
current class.
Fixes #221
> Allow subclasses to overwrite attributes

- changelog.d/253.breaking.rst
- docs/api.rst
- docs/examples.rst
- src/attr/_compat.py
- src/attr/_make.py
- tests/test_dark_magic.py
- tests/test_dunders.py
- tests/test_filters.py
- tests/test_funcs.py
- tests/test_make.py
- tests/utils.py
This behavior has been deprecated since 16.1 and can now be removed in
accordance with our backward-compatibility policy.
Interestingly, this simplified a lot of our code and might even improve performance of class creation.
> Stop setting attributes on class bodies

- conftest.py
- src/attr/__init__.py
- src/attr/_make.py
- src/attr/validators.py
- tests/test_annotations.py
- tests/test_dunders.py
- tests/test_filters.py
- tests/test_funcs.py
- tests/test_make.py
- tests/test_validators.py
This is a purely internal change.
The old internal names (that were also the old serious biz names) were kind of non-sensical so I’m moving the APIs to our newer ones that mirror the official names.
This PR doesn’t change any public APIs but makes sure that we have more consistent naming throughout the project.
This is something that has been annoying me for quite a while. *shiver*
> Use new serious biz names in internal code

- CONTRIBUTING.rst
- README.rst
As discussed in #247, this PR introduces the official `python-attrs` tag on StackOverflow and encourages people to help out with questions.
It’s very much overdue to have an official way.
***
As for live support: I really cannot bootstrap a new IRC channel and provide live support there.  There's a bunch of attrs users on #pylib so if they’d be so gracious to host us, I wouldn’t mind adding it the docs as a secondary help channel but so far, *this* is all *I* can commit to right now
fixes #247
> Document how to get help

- src/attr/_make.py
- tests/test_slots.py
Don't ask.
(Actually you can ask, hope the comments are enough.)
> Fix cell rewriting some more.

- changelog.d/282.change.rst
- docs/examples.rst
- src/attr/_make.py
- tests/test_dark_magic.py
- tests/test_make.py
Currently, trying to pickle an instance of a class created using `attrs.make_class` fails (tested on Python 2.7 and 3.5):
>>> import attr
>>> import pickle
>>> C = attr.make_class('C', ['x'])
>>> obj = C(1)
>>> pickle.dumps(obj)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class 'attr._make.C'>: attribute lookup C on attr._make failed
It has something to do with pickle looking for the class/type in the wrong module. I was curious how `collections.namedtuple` solves this and found this (also present in Python 2.7):
https://github.com/python/cpython/blob/v3.5.4/Lib/collections/__init__.py#L436-L445
This PR adds the same code (with comment) verbatim to attrs, to make pickling work. As a side effect, the `repr` of classes created …
> Fix pickling for instances of classes created using make_class()

- changelog.d/284.change.rst
- changelog.d/286.change.rst
- src/attr/_compat.py
- tests/test_slots.py
Testing makes it a bit convoluted but it works I guess.
Fixes #284
> Make ctypes optional

- changelog.d/285.change.rst
- changelog.d/287.change.rst
- src/attr/_make.py
- tests/test_make.py
Fixes #285 
When overwriting attributes from a deeper place, we need to check whether the deeper one is identical otherwise multiple inheritance screws up the order of attributes.
> Handle attrib redefs thru multiple inheritance

- changelog.d/291.change.rst
- changelog.d/292.change.rst
- src/attr/_make.py
- tests/test_annotations.py
Yeah, so this makes sure that if an empty class inherits `__annotations__` from a super class, those are ignored.  If there’s a better way, let me know.
Fixes #291
> Handle inherited __annotations__

- changelog.d/306.change.rst
- src/attr/_make.py
So this is a 1:1 implementation of the old behaviour, ignoring #305 for now.
Improvements:
```python
import attr
@attr.s(hash=True)
class C:
x = attr.ib()
y = attr.ib()
z = attr.ib()
c1 = C(1, "2", 3.0)
c2 = C(1, "2", 3.0)
```
attrs 17.3.0:
```
➤ pyperf timeit --rigorous -s "from t import c1, c2" "c1 == c2"
.........................................
Mean +- std dev: 3.24 us +- 0.13 us
```
New:
```
➤ pyperf timeit --rigorous -s "from t import c1, c2" "c1 == c2"
.........................................
Mean +- std dev: 538 ns +- 29 ns
```
For sets:
attrs 17.3.0:
```
➤ pyperf timeit --rigorous -s "from t import c1, c2" "s = {c1, c2}; c1 in s"
.........................................
Mean +- std dev: 8.56 us +- 0.32 us
```
New:
```
➤ pyperf timeit --rigorous -s "from t import c1, c2" "s = …
```
> Speed up __eq__ by generating code

- changelog.d/308.breaking.rst
- src/attr/_make.py
- tests/test_dunders.py
> Fix __repr__ crashing when a member is uninitialized or deleted

- changelog.d/298.breaking.rst
- changelog.d/299.breaking.rst
- changelog.d/304.breaking.rst
- docs/examples.rst
- src/attr/_make.py
- tests/test_make.py
So the double reversal we used to do screwed up the MRO traversal for forever (i.e. this is not a 17.3 regression, I had to fix examples.rst!).
This fixes it – the question is how we go about it.  A proper deprecation cycle seems impossible again, so I guess we can push it and ask for forgiveness?
This fixes #298 and #299 cc @yarikoptic
> Fix MRO traversal with multiple inheritance

- changelog.d/307.deprecation.rst
- docs/api.rst
- docs/examples.rst
- docs/extending.rst
- src/attr/_make.py
- tests/test_make.py
- tests/utils.py
> Rename convert to converter

- changelog.d/309.change.rst
- src/attr/_make.py
- tests/test_make.py
Fixes #309
Does this look good to you @Stewori?
> Add __module__ and __qualname__ to methods, fix __name__

- changelog.d/336.change.rst
- src/attr/_make.py
- tests/test_dark_magic.py
- tests/test_make.py
Non-frozen:
```
> pyperf timeit -g --rigorous --duplicate 5 -s "import attr; C = attr.make_class('C', ['a', 'b', 'c'])" "C(1,2,3)"
Mean +- std dev: 721 ns +- 29 ns
```
Before:
```
> pyperf timeit -g --rigorous --duplicate 5 -s "import attr; C = attr.make_class('C', ['a', 'b', 'c'], frozen=True)" "C(1,2,3)"
Mean +- std dev: 1.29 us +- 0.05 us
```
After:
```
> pyperf timeit -g --rigorous --duplicate 5 -s "import attr; C = attr.make_class('C', ['a', 'b', 'c'], frozen=True)" "C(1,2,3)"
Mean +- std dev: 738 ns +- 27 ns
```
That's an overhead of 17 ns per ~720, or 2.2%. It used to be 80%. I'd call that a win.
What's happening is that instead of using the cached setattr, we're now assigning directly to `self.__dict__`. Unfortunately, this trick works only for dict classes.
> Eliminate __init__ overhead for frozen dict classes.

- docs/why.rst
Since I get asked almost daily whether `attrs` will survive Python 3.7, I guess it’s time for a section on why we dare to think it’s worthwhile to not delete `attrs` from PyPI the moment 3.7 drops.
I’d like to ask @ericvsmith to rubber stamp this (or suggest changes) so it’s obvious it’s not some nefarious fake news propaganda.
If anyone can think of more reasons, please comment.
> Explain our position on Data Classes

- .gitignore
- changelog.d/300.change.rst
- changelog.d/339.change.rst
- changelog.d/343.change.rst
- src/attr/_compat.py
- src/attr/_make.py
- tests/test_make.py
> Retain order if these or make_class are passed an ordered dict

- .gitignore
This change ignores the `build/` directory, created by `python setup.py build`, with `git status`, etc.
While here, sort .gitignore entries.
> Ignore build/

- changelog.d/290.change.rst
- changelog.d/349.change.rst
- docs/api.rst
- src/attr/__init__.py
- src/attr/_make.py
- tests/test_make.py
This patch adds `attr.fields_dict()`, which returns an `OrderedDict` of `{attribute_name: Attribute}` for all attrs attributes of a class.
Closes #290.
I'm bad at describing dictionaries in prose, so feel free to improve. :)
> Add attr.fields_dict()

- docs/examples.rst
bytes are in the range 0..255, not 1...255.
> "fits_byte" validator should allow 0

- changelog.d/95.change.rst
- src/attr/_make.py
- tests/test_dunders.py
Fixes #95.
> - [x] Added **tests** for changed code.
Done.
There are no tests for the multithreaded case because it's literally impossible to test that, you just have to think really hard.  I could try harder if the reviewer thinks that this implementation strategy is risky but it seems pretty boring; just using threading.local to avoid sharing state between threads.
> - [ ] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/utils.py).
I don't *think* I need to do this here because I don't see anything relevant, but, I am not a Hypothesis expert so I might be missing something.
> - [ ] Updated **documentation** for changed code.
It's a bugfix, so I don't think it calls for updated docs.
Done.
> No recursion error for cycles in `repr`

- changelog.d/363.change.rst
- docs/examples.rst
- src/attr/_make.py
- tests/test_annotations.py
This just adds the annotations found at run-time to the
`__annotations__` attribute of the created `__init__` function
Fixes #249
> Annotate __init__ with type hints

- docs/hashing.rst
- docs/index.rst
It would be great if our resident hashing expert @njsmith could have a look too. :)
> Add a narrative chapter on object hashing

- src/attr/_make.py
- tests/test_annotations.py
Also updated the docstring to reflect why exactly we're doing what we're doing.
The previous comment was incorrect (`typing` is already imported in
applications using annotations).
I added `t.ClassVar` as well which is the only third alternative import I found
in use for typing-related classes.
Fixes #361
> Support `from typing import ClassVar`

- changelog.d/369.change.rst
- changelog.d/370.change.rst
- docs/api.rst
- docs/examples.rst
- docs/index.rst
- docs/init.rst
So it’s time to depend on examples even less.
Although the sections on validators and converters are copied mostly verbatim from there. I’m not sure how to cull examples in a meaningful way? It could be a little briefer and just refer to the new chapter.
But it finally gives a good place to explain intricacies of initialization.
Feedback welcome!
Fixes #289 #314 #264 #255 #263 #171 #107 #30
> Add narrative chapter about initialization

- docs/init.rst
A small typo in the exception message.
> Fix typo: double "be"

- src/attr/_make.py
- src/attr/filters.py
- tox.ini
The latter is not an invalid escape and Python 3.6+ complains about it.  I also
updated tox.ini so that those warnings are visible in the future.
Fixes #351
> Use `\\` instead of a single `\` in docstrings

- changelog.d/383.change.rst
- src/attr/validators.py
- tests/test_validators.py
> Improve error for in_(a_string) with a non-string value

- changelog.d/394.deprecation.rst
- src/attr/_make.py
- tests/test_make.py
Fixes #387 
The [docs](http://www.attrs.org/en/stable/api.html#attr.s) were always clear on this:
> But the attributes are *only* compared, if the type of both classes is *identical*!
(which sounds weird, so I fix it in this PR too)
> Raise DeprecationWarning when comparing subclasses

- changelog.d/364.change.rst
- changelog.d/396.change.rst
- conftest.py
- tests/test_funcs.py
We can always enable it when something seems off. As it stands now, it only makes our tests brittle.
Fixes #364
> Disable hypothesis.HealthCheck.too_slow globally

- .travis.yml
- tox.ini
> Run on 3.7 proper

- README.rst
- changelog.d/238.change.rst
- docs/index.rst
- docs/types.rst
- docs/why.rst
Narrative docs on type annotations to quell some of the FUD that is circulated.
> Add narrative docs for type annotations

- src/attr/converters.pyi
While working on adding this to the mypy plugin I came up with this annotation which helps capture errors better.  I don't think the change merits a changelog entry.
> Use an overload to get better type checking on default_if_none

- changelog.d/425.change.rst
- docs/api.rst
- docs/hashing.rst
- docs/init.rst
- src/attr/__init__.pyi
- src/attr/_make.py
- tests/test_dunders.py
- tests/test_make.py
- tests/utils.py
This adds a `cache_hash` flag to `@attrs` which causes the hash code to be computed once and stored on the object.  Setting this flag to `true` is allowed only if `attrs` is set to generate both the `__hash__` and `__init__` methods for a class.
This closes issues #423.
> Cache hash codes

- changelog.d/430.change.rst
- src/attr/_make.py
- tests/test_dark_magic.py
Fixes #429 by aliasing `property` and `itemgetter` to private names.
> Allow attributes to be called property and itemgetter

- AUTHORS.rst
- CHANGELOG.rst
- changelog.d/431.change.rst
- docs/how-does-it-work.rst
- src/attr/_make.py
- tests/test_annotations.py
- tests/test_dark_magic.py
- tests/test_make.py
Thanks to ABCs, "base class" is more Python than "superclass" and the latter is
also slightly confusing by alluding to "super" and/or being judgy.
Harmonize “subclass” while at it too.
> Consistently use "base class" and "subclass"

- docs/api.rst
Just added a parameter that was missing in the function defintion but existed below in the parameters section
> Added Core function parameter in func definition

- docs/examples.rst
I've always parsed this sentence as "attrs comes with serious, business aliases". I just realized you probably meant srs bzns aliases and figured I'd clarify.
> Improve sentence parsing

- docs/init.rst
> Clarify execution order in init

- .travis.yml
- pyproject.toml
- tox.ini
OK it would be nice to use properly isolated builds but it seems like mypy is [breaking](https://travis-ci.org/python-attrs/attrs/jobs/490956881) with it.
Maybe someone can help with that?
> Use isolated builds

- docs/index.rst
- docs/python-2.rst
Partly as another preparation for `import attrs`, I think it's good to spell out our Python 2 policy explicitly.
Feedback welcome!
> Add Python 2 statement

- .travis.yml
- changelog.d/500.change.rst
- docs/api.rst
- src/attr/__init__.pyi
- src/attr/_make.py
- tests/test_dark_magic.py
- tests/test_make.py
- tests/typing_example.py
Fixes #368
This adds first class exception support to `attrs`. While on the first sight it might make more sense to have an argument like `exc=True` or even have a separate decorator, I think in the ligtht of `import attrs` this approach is better, because – of course – `auto_exc` would be True by default in `@attrs.define`.
Let me know what you think or whether I've missed some subtleties.
~Open Questions:~
~1. Is it a good idea to put attributes with defaults into args too?~
~2. Should we add `init=False, default=NOTHING` too?~
~The more I look at the code I feel like it should be all (including default=NOTHING) or nothing (only non-default).~
> Implement first class exception support

- changelog.d/517.bugfix.rst
- src/attr/validators.py
- tests/test_validators.py
Apparently in #425 I forgot to add the new validators into `__all__`...PyCharm helpfully reminded me of this as soon as I updated a project to 19.1.0 and went to use them. x_x
> Fix validators __all__

- changelog.d/522.change.rst
- src/attr/_compat.py
- tests/test_slots.py
Instead of using ctypes, make a function that sets a cellvar and then fiddle with the code object to make it set a freevar instead. PyPy still uses `__setstate__` because it is easy and fast. I believe this is similar to the approach used by the `cloudpickle` package, but I didn't directly reference their code when writing this.
The performance of the new approach is comparable to the old one; timeit on py2.7 gives 645ns for the new approach (down from 691ns for the old), and on py3.6 gives 822ns for the new approach (up from 659ns for the old). And dropping the use of ctypes seems like a win.
This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution …
> Pure-Python approach to closure cell rewriting

- src/attr/_compat.py
- tests/test_funcs.py
- tests/test_slots.py
Automated using [yesqa](https://github.com/asottile/yesqa/) with the following command:
```bash
pre-commit try-repo https://github.com/asottile/yesqa/ --all-files
```
> Remove some extraneous # noqa comments

- azure-pipelines.yml
- src/attr/_compat.py
CodeType in 3.8 newly takes a posonlyargcount argument. (It also will add a replace() method that can be used to simplify this logic, but not until 3.8.0b1, which is too new for attrs' CI at the moment.) Fixes #538.
> Fix closure cell rewriting on 3.8

- docs/api.rst
- docs/examples.rst
The documentation already explains well why validator or default decorated methods
must not have the name of existing attributes (because they would be overridden).
This replaces the last remaining examples not using the explicit explanatory name.
> Rename remaining validator/default decorator examples with unclear names

- README.rst
I changed black link in readme, because black moved it under the PSF umbrella and link changed.
https://twitter.com/llanga/status/1153417050024550401
> Replace black link

- changelog.d/523.change.rst
- changelog.d/556.change.rst
- src/attr/_make.py
- tests/test_annotations.py
Fixes #523 
Classic None-as-sentinel-where-None-is-a-valid-value-blunder.
> Ensure that bare attributes with default None are removed too

- changelog.d/560.change.rst
- src/attr/_make.py
- tests/test_dunders.py
For debugging purposes, when a method is created it needs to be put
into a "filename".  This filename was generated using `repr(attrs)`
however this meant that the filename could change every time the
program was loaded depending on the whims of repr.  (In particular
free functions and lambdas would include ids)
This solves the problem by changing the name to be <attrs generated
{method} {module}.{qualname}> If it should happen that the name is
taken then -2 will be appended and incremented until a free filename
is found.
Fixes #558
I'll wait on a reply as to whether this is more or less what we were looking for before I go through the Pull Request checklist.
This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read …
> Make unique_filename not depend on repr.

- src/attr/_compat.py
- tests/test_slots.py
This was deferred from #539 because our CI didn't have a new enough 3.8 release at the time. `CodeType.replace()` is more forward-compatible, and the only 3.8 releases that don't support it are alpha releases with which we need not maintain compatibility.
> Update closure cell rewriting to use CodeType.replace() on 3.8

- changelog.d/543.change.rst
- changelog.d/563.change.rst
- src/attr/_make.py
- tests/test_dark_magic.py
They now behave as the docs claim.
Fixes #543
> Make auto_exc=True classes hashable by ID

- changelog.d/568.change.rst
- docs/examples.rst
- src/attr/__init__.pyi
- src/attr/_make.py
- tests/test_dunders.py
- tests/typing_example.py
This adds support for using a custom callable to be used instead of the default `repr()` when formatting individual attributes in the generated `__repr()__`. The `attr.ib(repr=…)` argument now takes either a `bool` (as before), or a callable that takes a value and returns a string.
Fixes #567. Fixes #212.
> support custom repr() callable for attributes

- changelog.d/570.breaking.rst
- src/attr/_make.py
- tests/test_make.py
This has been deprecated for a year and was raising a warning.
Done in preparation for splitting cmp in eq/order.
> Stop comparing/ordering subclasses

- changelog.d/580.change.rst
- docs/api.rst
- src/attr/__init__.py
- src/attr/__init__.pyi
- src/attr/_version.py
- src/attr/_version.pyi
- tests/test_version.py
- tox.ini
This allows users to check for features and avoid deprecation warnings without
breaking backward compatibility.
This is especially important with the cmp → order/eq split.
---
@euresti do I need to add it to `__init__.pyi` if it's an attrs class? I tried to just import it into it, but that started throwing errors about stuff in `_make.py`…
> Add attr.__version_info__

- changelog.d/585.change.rst
- src/attr/_make.py
- tests/test_annotations.py
> Fix default values that are not comparable with '=='

- src/attr/_make.py
> minor typo in attr.s docstring

- docs/how-does-it-work.rst
The mentioning of __attrs_attrs__ in a 'how does it work' document makes sense but it seems important to mention that there are good non-dunder ways to access the data.
WIP for:
> Mention attr.fields() after __attrs_attrs__ in 'How does it work'

- README.rst
- changelog.d/608.breaking.rst
- setup.py
- tox.ini
AP dropped it and there's really no reason to support it anymore. Xenial is on 3.5.
> Officially drop Python 3.4

- changelog.d/611.change.rst
- src/attr/_make.py
- tests/test_make.py
This uses the same mechanism to clear the cache hash as `__hash__` uses to set the cache hash in frozen classes - bypassing the object's `__setattr__` in favor of `object.__setattr__`. Neat trick.
Fixes #611.
- (N/A) New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/strategies.py).
- (N/A) Changes or additions to public APIs are reflected in our …
> Fixed frozen and cache_hash incompatibility

- changelog.d/611.change.rst
- changelog.d/620.change.rst
- src/attr/_make.py
- tests/test_dunders.py
- tests/test_make.py
When reviewing #615, @godlygeek came up with this brilliant alternative suggestion: use an `int` subclass that always pickles as `None`, so that unless someone goes out of their way to capture the cache value and include it in a `__reduce__` or `__setstate__`, the cache will be cleared on any copy operation.
My main fears (both of which turned out to be unsubstantiated) were:
1. This might slow down `hash()` in favor of correctness in serialization/deserialization for people implementing their own `__reduce__` functions, which seems like a very niche concern.
2. Returning a `_CacheHashValue` from `__hash__` might cause other problems, like if someone were taking the hash value of something and pickling or copying it for some deliberate reason (i.e. not copying the object it's stored on, …
> Use a wrapper class for cache hash to prevent cache serialization

- changelog.d/607.change.rst
- docs/api.rst
- src/attr/__init__.pyi
- src/attr/_make.py
- src/attr/exceptions.py
- tests/test_make.py
- tests/typing_example.py
This adds the feature to auto-detect existing methods so the creation doesn't have to be prevented by hand. This has been confusing our users for a while (see #324, #416).  It should become `True` by default when the new APIs emerge (attr.auto/attrs.define – this is actually one of the last blockers for me to start working on them).
Typing requires an update to the mypy plugin to work correctly (currently it says `tests/typing_example.py:193: error: Name '__init__' already defined on line 190`).
There is really only one controversial open question: if a method is detected, should it just prevent the one method or all of the related ones? E.g. if I define `__eq__`, what about `__ne__`?
I have decided to take the presence of _any_ method that belongs to a flag to set the flag to False …
> Add auto-detection of self-implemented methods

- changelog.d/428.change.rst
- changelog.d/635.change.rst
- docs/api.rst
- docs/extending.rst
- src/attr/_make.py
- tests/test_dark_magic.py
- tests/test_make.py
- tests/utils.py
This fixes #428 and has pestered me for a long while.
I'm not entirely sure how to go forward with the option, I guess I'll just set it to `True` in `@attrs.define`?
Anyhow, I this is the penultimate ticket stopping me from tackling the new APIs…
> Fix attribute collection

- setup.py
This typo was noticed when copy/pasting the `read` function into my own
`setup.py`.
Thanks a lot, Hynek!
modified:   setup.py
- [-] Added **tests** for changed code.
- [-] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/master/tests/strategies.py).
- [-] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
- [-] ...and used in the stub test file `tests/typing_example.py`.
- [-] Updated **documentation** for changed code.
- [-] New functions/classes have to be added to `docs/api.rst` by hand.
- [-] Changes to the signature of `@attr.s()` have to be added by hand too.
- [-] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` …
> Fix typo in `setup.py`

- docs/extending.rst
This fIxEs  #630 as far as _we_ can fix it. I would love to add a more concrete example (a minimal example that people can just drop in and that explains _how_ to drop in) but I guess I'll leave that as a contribution opportunity to someone else since I don't have the bandwidth for that ATM.
> Document how to write aliases that are recognized by mypy

- docs/types.rst
If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing left to do.
> Add documentation about string annotations

- src/attr/_next_gen.py
- tests/test_next_gen.py
By setting eq to True by default, it forces `__eq__`/`__ne__` to be written. Setting to None fixes it.
fixes #670
> Fix auto-detection of eq/ne in NG APIs

- docs/init.rst
> Doc typo: into -> in

- changelog.d/685.change.rst
- pyproject.toml
- setup.py
- tests/test_validators.py
- tox.ini
For the admittedly small number of people who don't care about support for `zope.interface`, it is unnecessary extra work to support even a test-only dependency on `zope`.
The `zope`-specific tests are relatively contained, however, and with judicious use of pytest fixtures, we can make it so that `zope` is not a required dependency when skipping tests marked with `pytest.mark.zope`.
This allows users to test everything but the `zope`-specific tests with no `zope` dependency with:
```
$ TOX_AP_TEST_EXTRAS="tests_no_zope" tox -e <env> -- -m 'not zope'
```
I realize that this is unusual and maybe not a maintenance burden you want to carry upstream, but it would smooth the process of importing `attrs` upstream into a certain large company's monorepo... I'm fine with a response that's …
> Make `zope` a semi-optional test dependency

- changelog.d/684.change.rst
- src/attr/_make.py
- tests/test_make.py
Although technically, `inherited` is part of the structure, practically it exposes a very confusing behavior because by subclassing the attribute suddenly doesn't compare equal although it _is_ equal by all logical standards.
fixes #682
> Ignore inherited field when comparing Attributes

- changelog.d/687.change.rst
- src/attr/_next_gen.py
- tests/test_next_gen.py
This is a fix for an inconvenience that @euresti mentioned in https://github.com/python-attrs/attrs/issues/668#issuecomment-678689981.
`on_setattr=validate` gets into the way if you want to pass `define(frozen=True)` or if you subclass a frozen class using `define`.
The new logic should catch these problems.
> NG: make frozen classes comfortably subclassable

- changelog.d/653.change.rst
- conftest.py
- docs/api.rst
- docs/extending.rst
- src/attr/__init__.pyi
- src/attr/_funcs.py
- src/attr/_make.py
- src/attr/_next_gen.py
- tests/test_hooks.py
- tests/test_make.py
- tests/typing_example.py
Improve (de)serialization and validation capabilities by adding hooks that can automatically update a class’ attributes and that can change the way how objects are serialized by `asdict()`.
See: #649
If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing left to do.
> Improve (de)serialization and validation capabilities

- changelog.d/704.change.rst
- src/attr/_funcs.py
- tests/test_funcs.py
> Treat frozensets like sets in asdict/astuple

- changelog.d/700.change.rst
- changelog.d/700.changing.rst
- docs/examples.rst
- src/attr/_make.py
- tests/test_make.py
Hello!
Thank you for bringing an awesome package and supporting Python 2 in 2020!
In my experience I find kw_only attributes really addictive, as they allow to inherit from classes ignoring attributes with defaults. Unfortunately, they don't work on Python 2, so it's actually impossible to write some compatible code. 
Even writing `__init__` by hand:
```python
@attr.s(kw_only=not PY2)
class Base(object):
kw_only1 = attr.ib(default=None)
kw_only2 = attr.ib(default=42)
@attr.s(init=not PY2)
class Child(Base):
attr1 = attr.ib()
attr2 = attr.ib()
if PY2:
def __init__(self, attr1, attr2, **kwargs):
super(Child, self).__init__(**kwargs)
self.attr1, self.attr2 = attr1, attr2
```
Will fail, as `attrs` disallows mandatory attributes after an attribute with a default value or factory. Even this …
> [RFC] kw_only python 2 backport

- tests/strategies.py
This PR refactors two Hypothesis strategies which are used to test `attrs`, in one commit each:
1. In `simple_classes()`, we draw boolean flags for `frozen`, `slots`, and `weakref` *even if we will not use them*.  This means that from Hypothesis' perspective the data structure does not depend on whether the flags will be used, which in turn makes mutation and shrinking logic a little more efficient.
2. Refactoring `_create_hyp_nested_strategy()` to use the `@st.composite` decorator.  This makes the code considerably shorter, and IMO the imperative style is also much easier to read in this case.
> Refactor Hypothesis strategy for self-tests

- changelog.d/703.change.rst
- changelog.d/712.change.rst
- pyproject.toml
- src/attr/_compat.py
- src/attr/_make.py
- tests/test_next_gen.py
> Fix exception chaining on PyPy

- docs/init.rst
It took me a moment of staring at this example to realise that `i` and `j` were actually different variables. They're not very different in the monospaced font!
I'm hoping that `i` and `k` will make them stand out more, and this example easier to read.
(Most letters seem to have a use already in this file, or I'd have picked an even more different pair of letters.)
—
If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing left to do.  If your pull request is a documentation fix or a …
> Use 'i' and 'k' to better distinguish variables in an example

- changelog.d/747.change.rst
- src/attr/_make.py
- tests/test_slots.py
> Fix: TypeError when using properties, super(), and slots=True (#652)

- changelog.d/750.change.rst
- src/attr/_make.py
- tests/strategies.py
- tests/test_dunders.py
- tests/test_make.py
> __attrs_pre_init__

- src/attr/converters.py
Just noticed this while reading through the docs. It's a 1 character change, so if you'd prefer to fix this in a bigger commit, feel free to close this. 
If you want to pull this in, I believe the docs auto-pull from the docstrings, but let me know if I need to do anything other than this. 
If you have *any* …
> doc: fix typo in default_if_none doc

- src/attr/_make.py
- tests/test_annotations.py
This fixes #593 
I factored out the call to eval(compile... and added a generic `_make_method` method to remove repeated code.
> Fix issue with get_type_hints(cls.__init__) and refactor

- changelog.d/759.change.rst
- docs/examples.rst
- src/attr/_funcs.py
- tests/test_funcs.py
> Recursively evolve nested attrs classes

- .github/workflows/main.yml
- conftest.py
- setup.py
- src/attr/_make.py
- tests/test_annotations.py
- tests/test_dunders.py
- tests/test_funcs.py
- tox.ini
Python 3.10 has string types everywhere and that has unmasked a bunch of
bugs/edge cases in our code.
Especially the hooks code need a resolving helper for string types. I'm leaving
that for a separate PR.
Same for test_mypy.yml
Fixes #716
cc @euresti @ambv @frenzymadness @sscherfke
> Add Python 3.10 support

- docs/init.rst
I'm new to the project, but I noticed that one of references to `__attrs_post_init__` had _two underscores_ after the `post` like `__attrs_post__init__`. This seems like a typo because elsewhere it only has one underscore there.
----
If you have *any* questions to *any* of the points above, just **submit and ask**! …
> Fix possible typo in init.rst

- docs/comparison.rst
- docs/index.rst
These are some narrative docs for #627, I'm open to suggestions to make it juicier.
Here's the built version: https://attrs--768.org.readthedocs.build/en/768/comparison.html
@Julian @botant
> Document comparison

- changelog.d/774.change.rst
- conftest.py
- src/attr/__init__.pyi
- src/attr/_funcs.py
- tests/test_hooks.py
This was discussed in #766 .  Let me know how you like it.  
> Add attribs to resolve_types and fix test_hooks

- src/attr/_make.py
E.g. (from https://grammar.yourdictionary.com/grammar-rules-and-tips/double-negative-trouble.html):
> > Neither fish nor chicken weren't at the party.
>
> This sentence contains a double negative because "neither" and "weren't" are both negatives. "Neither fish nor chicken were at the party" would be fine, as would "Fish and chicken weren't at the party.
> docs: fix double negative

- changelog.d/782.change.rst
- src/attr/_make.py
- tests/test_annotations.py
Fixes #781
@graingert @euresti
> Detect ClassVars coming from typing_extensions

- src/attr/__init__.pyi
- tests/typing_example.py
This changes the annotations for `attr.Factory` so that the acceptable type of the callable changes based on `takes_self`.
Theoretically, MyPy will let you do this:
```py
attr.ib(default=attr.Factory(list, takes_self=True)
attr.ib(default=attr.Factory((lambda self: []), takes_self=False)
```
The change in annotations will prevent that from happening.
As written I *think* these annotations would require the type checker to be running on Python 3.8 because of the use of `Literal`. There are a couple ways around this, if necessary.
> Narrower typing on Factory called with takes_self

- changelog.d/668.change.rst
- changelog.d/786.change.rst
- docs/api.rst
- docs/comparison.rst
- src/attr/_next_gen.py
I think it's time to go this step! I've been using these APIs in production _exclusively_ and the feedback to them was overwhelmingly positive. They are also officially supported by Mypy without any plugin hacks.
Fixes #668
> Make NG APIs official

- src/attr/_make.py
The intent is to avoid catching readers off guard from the contradiction between "assigning Factory will work as expected" and the subsequent warning.
Raised in #788
> docs: more explicit about Factory caveats

- docs/overview.rst
> fix: small error in docs

- src/attr/__init__.py
- src/attr/__init__.pyi
- src/attr/_cmp.py
- src/attr/_cmp.pyi
- tests/test_cmp.py
- [?] ...and used in the stub test file `tests/typing_example.py`.
> New attr.cmp_using helper function

- .github/workflows/main.yml
Apparently, a last-minute change made it into 3.10.beta1 that broke pytest.
> Pin 3.10 to last alpha

- src/attr/_make.py
- tests/test_make.py
Since this warning is raised from the attr.ib/attr.field call, we cannot verify
whether order is on at all for the whole class. Fixing this would require to
check _after_ the class is assembled which is both additional complexity as
well as performance overhead. Unless we get inundated by bug reports, this
doesn't seem worth it.
@botant @Julian
> Remove warning if eq is customized & order is not

- changelog.d/796.change.rst
- docs/extending.rst
- docs/types.rst
- src/attr/__init__.pyi
- tests/dataclass_transform_example.py
- tests/test_pyright.py
- tox.ini
Implements baseline support for `pyright` as described in #795.
> Implement pyright support via dataclass_transforms

- setup.py
Python 3.4 testing has been dropped in #608, but it was not declared as incompatible in setup.py because the code base was expected to still work with Python 3.4 for a while. This compatibility finally broke with the 21.1.0 release. At least one of the problematic commits is e09b1d642339d7d94ba58d7855da40e65ed1a88f introducing an import of the typing module not available in Python 3.4.
Trying to import attr with Python 3.4 gives the following exception:
```
>>> import attr
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/gosmannj/Documents/projects/attrs/.venv/lib/python3.4/site-packages/attr/__init__.py", line 7, in <module>
from . import converters, exceptions, filters, setters, validators
File …
```
> Declare Python 3.4 as incompatible

- changelog.d/817.change.rst
- src/attr/_make.py
- tests/test_dunders.py
- tests/test_functional.py
This is important because define/mutable have on_setattr=setters.validate on
default.
Fixes #816
> Optimize the case of on_setattr=validate & no validators

- .pre-commit-config.yaml
- CHANGELOG.rst
- changelog.d/815.changes.rst
- conftest.py
- docs/api.rst
- pyproject.toml
- src/attr/__init__.pyi
- src/attr/_make.py
- src/attr/_next_gen.py
- tests/test_make.py
- tests/test_pattern_matching.py
- tests/typing_example.py
- tox.ini
> Add __match_args__ to support match case destructuring in Python 3.10

- changelog.d/819.changes.rst
- src/attr/_compat.py
- src/attr/_make.py
Initial implementation, CHANGELOG to follow.
Benchmark used:
```
pyperf timeit -g -s "from attr import make_class, attrib; A = make_class('A', ['a', 'b', 'c', 'd', 'e']); a = A(1, 2, 3, 4, 5)" "repr(a)"
```
Old code:
```
Mean +- std dev: 2.09 us +- 0.07 us
```
New code:
```
Mean +- std dev: 957 ns +- 27 ns
```
> Initial implementation of a faster repr

- tests/test_mypy.yml
Mypy changed how it returns a lot of errors, so we must too
> Fix the mypy tests by double quoting.

- conftest.py
- tox.ini
Looks like this was a bug fixed upstream
Fixes #767
> Fix mypy tests on 3.10

- changelog.d/828.changes.rst
- src/attr/_make.py
- tests/test_dunders.py
Working version of a fix for #826
We deduplicate linecache entries, thus avoiding identical class creation time increasing linearly and saving memory in the process.
> Rework linecache handling

- tests/test_mypy.yml
Looks like the ordering changed
> Fix mypy tests.

- src/attr/__init__.py
- tests/attr_import_star.py
- tests/test_import.py
I have no idea why one would want to type this, but it is broken right now on Python >= 3.6. This PR should fix that.
> Make `from attr import *` work again on recent python versions.

- tests/test_mypy.yml
> Fix mypy tests.  Looks like the tests are error order sensitive

- src/attr/_compat.py
CPython 3.6 has f-strings:
```
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> f"hello"
'hello'
```
---
A quick thing I noticed. Feel free to reject if there's an assumption I'm missing (e.g. a feature of f-strings that was introduced after 3.6 that attrs uses).
Checklist: All N/A.
> Enable use of f-strings in Python 3.6.

- changelog.d/847.change.rst
- setup.py
- src/attr/_compat.py
- src/attr/_make.py
- tests/test_compatibility.py
- tests/test_dunders.py
Generated `__repr__` methods for Pythons with f-strings included
a `threading.local` object in that method's `globals()` dictionary.
Because `cloudpickle` attempts to serialize all globals of this method,
it ends up trying to pickle the `threading.local`, which cannot be
pickled.
Instead, we now pull use of the thread-local out into its own function,
which `cloudpickle` will happily serialize. As an added benefit, this
eliminates some duplicated code between f-string and non–f-string
`__repr__`s.
Should fix:
- https://github.com/python-attrs/attrs/issues/458
- https://github.com/cloudpipe/cloudpickle/issues/320
I'm not sure what the best direction to go on this is. I run this locally and see that when I cloudpickle an attrs class, it works fine. It would be pretty simple to add a test dep …
> Pull threading.local out of the generated repr's globals.

- README.rst
- docs/api.rst
- docs/glossary.rst
- docs/how-does-it-work.rst
- docs/index.rst
- docs/names.rst
- docs/overview.rst
This is an addendum to #863 and fixes #726.
N.B. that you can read the rendered docs at https://attrs--871.org.readthedocs.build/en/871/names.html
> Document the various core names and why they exist

- changelog.d/877.change.rst
- src/attr/validators.py
- src/attr/validators.pyi
- tests/test_validators.py
- tests/typing_example.py
Fixes #875.
This adds support for pre-compiled regular expressions to
attr.validators.matches_re(). This cannot be combined with flags since
the pre-compiled pattern already has those.
Detailed changes:
- attr.validators.matches_re() now accepts re.Pattern in addition to
strings; update type annotations accordingly.
- Convert percent-formatting into str.format() for an error message
- Simplify (private) _MatchesReValidator helper class a bit: use the
actual compiled pattern, and drop the unused .flags attribute.
- Simplify control flow a bit; add pointer about fullmatch emulation.
- Add tests
- Tweak existing test to ensure that .fullmatch() actually works
correctly by matching a pattern that also matches (but not
‘full-matches’) a shorter substring.
> Add support for re.Pattern to validators.matches_re()

- src/attr/__init__.pyi
It got accidentally removed in https://github.com/python-attrs/attrs/pull/787/commits/6f5c5ce42f5c406e446dd3d4863c17f61c7254a7
fixes #883
> Add _CompareWithType

- docs/examples.rst
- docs/types.rst
More more doc modernization.
I have come across a problem though.
```
from attr import define, fields, resolve_types
@define
class A:
a: list["A"]
b: "B"
@define
class B:
a: A
print(fields(A).a.type)
fields(A).b.type
resolve_types(A, globals(), locals())
print(fields(A).a.type)
fields(A).b.type
```
This is from the docs but it doesn't actually work. `typing.List["A"]` will produce a ForwardReference by itself, but `list["A"]` won't, so `typing.get_annotations` doesn't process it. What a nasty surprise.
> Modernize docs some more

- changelog.d/646.change.rst
- changelog.d/888.change.rst
- src/attr/__init__.pyi
- src/attr/_funcs.py
- tests/test_funcs.py
- tests/typing_example.py
This allows to have collection-esque keys in dict.
I have decided to switch it on by default if retain_collection_types is false, because the current behavior is non-sensical.
Fixes #646
Needed for #887 
This is just a friendly reminder about the most common mistakes.  Please make sure that you tick all boxes.  But please read our [contribution guide](https://github.com/python-attrs/attrs/blob/main/.github/CONTRIBUTING.md) at least once, it will save you unnecessary review cycles!
If you have *any* questions to *any* of the points above, just **submit and ask**!  This …
> Serialize keys as tuples in asdict

- docs/why.rst
This is to fix #761
There's a bunch of problems to discuss, so I'm just gonna start _somewhere_.
The big questions to me are:
- do we still have to talk about dicts/tuples at all?
- should we add pydantic? (cf. <https://threeofwands.com/why-i-use-attrs-instead-of-pydantic/>)
- **how** are we going to talk about dataclasses at all, since they're something else in each Python release?
- https://attrs--872.org.readthedocs.build/en/872/overview.html
- https://attrs--872.org.readthedocs.build/en/872/why.html
> Update comparisons to dataclasses

- README.rst
> Remove typo in README.rst

- docs/api.rst
Very minor typo in docs (and a few other questions/points).
Thank you for the great release with 21.3.0... I have already updated a big project I'm working on to use it. :-)
I found this minor typo in the docs.
Also, a couple of other points questions if you don't mind -- I normally wouldn't bring these up in a PR, but since I'm not sure of another place to discuss this, I thought this was better than nothing:
This is really minor, but the phrase "vastly popular" in `docs/names.rst` feels a bit awkward to me.  I would expect to see "vastly more popular" if the intent is "people are abandoning the previous way in droves" or "very popular" if the intent is "people seem to really like the new way".  I wasn't sure the intended meaning, so I didn't include this in the PR and just wanted to …
> docs: fix very minor typo

- .github/workflows/main.yml
- changelog.d/892.change.rst
- setup.py
- tests/test_3rd_party.py
The cloudpickle package relies on CPython implementation details,
and does not even import on PyPy:
```
ImportError while importing test module '/tmp/attrs/tests/test_3rd_party.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/pypy3.8/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
tests/test_3rd_party.py:7: in <module>
import cloudpickle
.tox/pypy3/lib/pypy3.8/site-packages/cloudpickle/__init__.py:4: in <module>
from cloudpickle.cloudpickle import *  # noqa
.tox/pypy3/lib/pypy3.8/site-packages/cloudpickle/cloudpickle.py:57: in <module>
from .compat import pickle
.tox/pypy3/lib/pypy3.8/site-packages/cloudpickle/compat.py:13: in <module>
from _pickle import Pickler  # noqa: F401
E …
```
> Do not require cloudpickle for PyPy

- changelog.d/895.change.rst
- changelog.d/896.change.rst
- src/attr/_make.py
> Make virtual repr file names unique

- changelog.d/898.change.rst
- docs/how-does-it-work.rst
- src/attr/_make.py
- tests/test_functional.py
I was playing around seeing if I could speedup the creation of frozen slot classes for a project of mine since we instantiate a lot of attr classes. Ideally they would be frozen, but we didnt go with it because of the speed implications it had.
To try and speed it up I tried different things:
- Make use of `objects.__setattr__` during the whole of the init and then place the frozen one at the end
- The idea behind this is to use the default `__setattr__` during the whole `__init__` function and then setting it to the frozen one after, which I thought would bring speedups as well as improve the UX, since they can could set attributes normally in the init. This unfortunately didnt work nicely with slots and slowed it down even further when attempting a workaround
- Playing around a bit with …
> Speedup uses of `object.__setattr__`

- src/attr/_next_gen.py
Both `attr.define` and `attr.s` have `match_args=True` by default.
> Remove incorrect statement in documentation

- changelog.d/898.change.rst
- changelog.d/909.change.rst
- src/attr/_make.py
- tests/test_make.py
Thanks for making attrs btw! It's an amazing library. In the documentation for `attr.ib` (sorry, still speaking in 2021 attr here), we see:
> hash (Optional[bool]) – Include this attribute in the generated __hash__ method. If None (default), **mirror eq’s value**. This is the correct behavior according the Python spec. Setting this value to anything else than None is discouraged.
Currently this does not happen - if we passed in a `callable` to transform the field's value, we would see `_x_key(self.x)` in the generated eq code, but we don't see the same thing happening for the generated hash function.
Currently, I'd like to compare equality of a non-hashable object. I was surprised to see that the hash function did not respect the `eq` override and get it for free (which is an awesome …
> Fix hashing for custom `eq` objects

- src/attr/_make.py
Hi!
I am implementing `match_args` support in Mypy and while reading your docs I was confused: how can `attr.s` work with *positional-only* arguments to `__init__`?
By *positional-only* many python devs mean this: `def some(x, y, /): ...`
But, this is not the case for `attr.s`, proof:
```python
import attr
@attr.s(match_args=True, auto_attribs=True)
class ToMatch:
x: int
y: int
z: int = attr.field(kw_only=True)
print(ToMatch(1, 2, z=3).__match_args__)  # ('x', 'y')
print(ToMatch(x=1, y=2, z=3).__match_args__)  # ('x', 'y')
```
As you see, here both `x` and `y` are regular arguments, they can be passed by position or by name.
So, I hope that the proposed wording will be cleaner! 👍
> Improve docs of `attr.s(match_args=True)`

- src/attrs/__init__.pyi
- tests/typing_example.py
Basically we forgot to export converters and filters and the import checks didn't catch that.
Fixes #930
> Add missing attrs.converters/filters, fortify type tests

- docs/examples.rst
neither attrs as a whole nor field is imported from attrs. Therefore the example using field does not work if one goes through the examples step by step. either import fields from the beginning (as suggested) or in the example using fields.
> fields needs to be imported in examples

- .pre-commit-config.yaml
- changelog.d/925.change.rst
- src/attr/validators.py
- src/attr/validators.pyi
- tests/test_validators.py
Proposed fix for #924 
Allows users to pass in a list of validators within the member validator of the `deep_iterable` validator. I feel this makes it more consistent with what users would expect. I atleast had a minor use case when using `attrs` and thought it would be worthwhile to support this.
This PR contains:
- Small tweak to the `deep_iterable` validator
- Updates to the doc string of `deep_iterable`
- Tests for the new behaviour (backward compatible)
- Minor doc string fix in a different test
If people think this is useful I would be happy to make a different PR to support the same for the `deep_mapping` validator
Find the appropriate next version in our [``__init__.py``](https://github.com/python-attrs/attrs/blob/main/src/attr/__init__.py) …
> Allow `deep_iterable` member validator to accept a list of validators

- changelog.d/939.breaking.rst
- src/attr/_make.py
- tests/test_functional.py
This has nothing to do with the cmp argument to attr.s/define which have been
undeprecated.
> Drop the deprecated Attribute.cmp

- docs/api.rst
- docs/examples.rst
- docs/init.rst
- docs/names.rst
- docs/types.rst
- docs/why.rst
- tests/test_mypy.yml
This is no longer relevant in Python 3+. Follow-up to !936.
> No longer explicitly subclass ‘object’

- docs/glossary.rst
- docs/hashing.rst
- src/attr/_compat.py
- src/attr/validators.py
- tests/test_slots.py
- Reword and simplify a few docstrings.
- Add back a test for 2-arg super() in property() definitions that
was (accidentally?) dropped in #936.
> Clean up some more Python 2-isms

- docs/examples.rst
- docs/init.rst
this PR adds the import statement for `@frozen` decorator to maintain consistency; also fix an indention error in `init.rst`.
Only documentation changes is included, remove check list.
> Update docs/examples.rst: add missing import statement for @frozen

- docs/extending.rst
Removed mutable default arg, replaced with `None`.
https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html
Replaced `dict()` with `{}`.
https://stackoverflow.com/questions/8424942/creating-a-new-dictionary-in-python
Documentation changes.
> Remove mutable default arg in function example

- changelog.d/949.change.rst
- docs/comparison.rst
- src/attr/__init__.pyi
- src/attr/_cmp.pyi
- src/attrs/__init__.pyi
- tests/typing_example.py
Fixes  #948
cc @botant @Julian
> Add missing cmp_using to stub files

- docs/api.rst
Should read top-level, not to-level.
Typo fix in API documentation
> Typo fix in api documentation

- .github/workflows/main.yml
- setup.py
- src/attr/_compat.py
- tests/test_annotations.py
- tests/test_make.py
- tests/test_slots.py
- tox.ini
> Add support for Python 3.11

- tests/test_annotations.py
There is a small typo in tests/test_annotations.py.
Should read `converter` rather than `coverter`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, coverter -> converter

- .github/CONTRIBUTING.md
Fixes a typo to the Tox Wiki in CONTRIBUTING.md.
> Fix typo in tox wiki link in CONTRIBUTING.md

- .github/workflows/main.yml
- .pre-commit-config.yaml
- README.rst
- changelog.d/988.breaking.rst
- conftest.py
- docs/api.rst
- docs/examples.rst
- docs/extending.rst
- docs/names.rst
- setup.py
- src/attr/__init__.py
- src/attr/_compat.py
- src/attr/_make.py
- src/attr/_next_gen.py
- src/attr/converters.py
- src/attr/validators.py
- tests/attr_import_star.py
- tests/test_annotations.py
- tests/test_funcs.py
- tests/test_functional.py
- tests/test_init_subclass.py
- tests/test_make.py
- tests/test_next_gen.py
- tests/test_pyright.py
- tox.ini
Less than 0.5% of our downloads are 3.5 and it allows us to simplify A LOT of code. Just look at all the beautiful (and fast) f-strings (they're courtesy of pyupgrade).
Fixes #965
> Drop Python 3.5

- changelog.d/991.change.rst
- docs/how-does-it-work.rst
- src/attr/_make.py
- tests/test_functional.py
Fix slight performance regression of #898.
I only noticed this after upgrading to 22.1.0, but the PR i made a while back to speedup the instantiation of frozen classes did so, but at a cost of not scaling correctly the more attributes that need to be set
Didnt want to just revert the commit, so played around a bit and found some optimizations. which are in this pr. They include (partially) going back to some of the old code, but with some optimizations that makes it both scale better and perform better in simple tests, ending up being a win win. Sorry for the slight performance regression this issue caused. It didnt cross to me it wouldnt scale well.
<details>
<summary>3 arguments performance</summary>
```
$ pyperf timeit --rigorous -s "import attr; C = attr.make_class('C', ['x', 'y', …
```
> Speedup `_setattr` usage and fix slight performance regressions

- conftest.py
- tests/test_annotations.py
- tests/test_dunders.py
- tests/test_functional.py
- tests/test_init_subclass.py
- tests/test_make.py
- tests/test_setattr.py
- tests/test_slots.py
Actually use it a few times while at it.
> Replace omnipresent pytest.mark.parametrize("(slots|frozen)" w/ fixture

- changelog.d/1001.change.rst
- conftest.py
- src/attr/_make.py
- tests/test_abc.py
I've found this feature while researching #1000.
Unfortunately it didn't fix that particular problem, but it still seems useful.
> Call abc.update_abstractmethods on 3.10+

- src/attr/_make.py
- tests/test_slots.py
We use a dict instead of a tuple, so that we assign only existing attributes on unpickle, if the class
definition has changed in the meantime.
Resolves #1004
> Change __getstate__ and __setstate__ to use a dict (#1004)

- .github/workflows/main.yml
$sbj. Invoking `python -m build --sdist --wheel` builds an sdist and a wheel from the project source directory (i.e. from the Git checkout). Each of them. It is recommended to make sure that it's possible to build a wheel from an sdist and not from a Git repo since some files may be excluded while building an sdist making the artifact essentially broken (kinda). `pip install` normally attempts building a wheel before installing from sdist, it also caches it.
Starting around v0.5.0 of `build`, it builds and sdist followed by building a wheel _from that sdist_. But only if you don't specify any of `--sdist` or `--wheel` explicitly. If you do, it'll build from your repo checkout.
This patch makes sure that this kind of smoke testing actually happens in the CI.
> Build sdist from a wheel in CI

- .github/CONTRIBUTING.md
- .github/workflows/main.yml
- pyproject.toml
- setup.py
- tox.ini
Locally, this slashes over 70% of runtime.
Let's see what it does to CI.
> Use pytest-xdist in tox / CI

- .github/CONTRIBUTING.md
It was using RST but the doc is actually in Markdown.
> Fix pre-commit link syntax in contributing doc

- changelog.d/1016.doc.rst
- docs/changelog.rst
- docs/conf.py
- setup.py
This change integrates `sphinxcontrib-towncrier` into the docs build.
It uses Towncrier and its configs to render a draft changelog as RST
and injects that into the `changelog.rst` document right above the
older changelog entries using `towncrier-draft-entries` directive.
I figured, it'd be nicer to be able to have a sneak-peak into the future
release changes. As an alternative to navigating to a folder with a
bunch of standalone uncategorized files.
Usage in the wild: https://pip.pypa.io/en/latest/news/#not-yet-released-2022-08-21.
Preview: https://attrs--1016.org.readthedocs.build/en/1016/changelog.html#changelog.
> Add a preview for the "next release" change notes

- changelog.d/1017.deprecation.rst
- changelog.d/988.breaking.rst
- src/attr/__init__.py
> Deprecate Python 3.6

- changelog.d/999.change.rst
- src/attr/__init__.py
- src/attr/__init__.pyi
- src/attr/_typing_compat.pyi
- src/attrs/__init__.py
- tests/test_pyright.py
- tox.ini
MyPy treats the user-declared `MYPY` constant equivalently
to `typing.TYPE_CHECKING` (see https://mypy.readthedocs.io/en/stable/more_types.html#conditional-overloads).
This can be used to trick other type checkers into ignoring
MyPy-specific types.
`AttrsInstance` needs to be declared in a separate stub file so as to
not export `MYPY`.
> Fix type errors in Pyright

- .github/workflows/ci.yml
This patch updates the use of Python 3.11 in CI to the newly released stable version, in the test jobs. It also moves the non-test jobs from Python 3.10 to 3.11
> Use the stable version of Python 3.11 in CI

- .github/workflows/ci.yml
22.04 has no Python 3.6 anymore.
> Pin test CI image to ubuntu 20.04 for one more release

- .github/workflows/ci.yml
- src/attr/_compat.py
- tests/test_abc.py
- tox.ini
Ref https://github.com/python-attrs/attrs/pull/1029#issuecomment-1261394538.
This is kept as a draft that is expected to be merged once all of the following are true:
> Add unstable Python 3.12 to CI allowing failures

- docs/api.rst
- src/attr/_make.py
> Clarify make_class argument type

- changelog.d/1081.change.md
- src/attr/_make.py
- tests/test_next_gen.py
This code previously raised an `attrs.FrozenInstanceError`:
```python
from contextlib import contextmanager
from attrs import frozen
@frozen
class Boom(Exception):
pass
@contextmanager
def do_nothing():
yield
with do_nothing() as _:
raise Boom()
```
on CPython (3.11 specifically, but probably other versions). On PyPy, it works, at least on 3.9 here -- which means I think it seems reasonable to merge the two codepaths here as I've done rather than whitelisting different attributes on different interpreters, but lemme know if you disagree.
(In real life a likely way you're going to encounter this, just to help anyone searching, is that `click` will wrap all exceptions during execution of a program, and does so via a `contextlib.contextmanager`)
Refs #712
Our CI fails if coverage is not …
> Fix @frozen exceptions to allow __traceback__ to be set.

- changelog.d/1084.change.md
- src/attr/__init__.pyi
- tests/dataclass_transform_example.py
- tests/test_pyright.py
Currently, `@frozen` does not disallow setting instance properties in type checkers that implement [PEP-681](https://peps.python.org/pep-0681/). Now the following is marked as an error in both mypy and pyright:
```python
from attrs import frozen
@frozen
class Frozen:
a: str
f = Frozen("a")
f.a = "new"
```
> Fix @frozen typing to work on PEP-681 checkers

- changelog.d/1090.change.md
- src/attrs/__init__.pyi
- tests/test_mypy.yml
Fixes https://github.com/python-attrs/attrs/issues/1089
`AttrsInstance` protocol was added in https://github.com/python-attrs/attrs/pull/890 but two functions in the `attrs` namespace were apparently forgotten and still accept Any as the instance. This PR changes the signatures to accept `AttrsInstance` instead to match what's in the `attr` namespace.
> Add AttrsInstance protocol to forgotten attrs.asdict and attrs.astuple

- changelog.d/1085.change.md
- src/attr/_make.py
- tests/test_slots.py
Unfortunately we're using `django-redis` to cache some `attrs` instances and the change to make `__getstate__` and `__setstate__` use `dict` values instead of `tuple` values prevents reading any values from the cache when updating to `attrs>=22.2.0`. We get an `AttributeError` raised for all attributes.
This happens because the tuple of values stored in the original pickle is checked for the name of the attribute and so none of the attributes are set on unpickle.
To address this I've made a change so that `__setstate__` will still be able to handle values pickled as `tuple`s allowing existing pickles to be unpickled.
The test just contains a pre-pickled value due to the complexities around tying to mock methods on a slotted as documented[^1].
I realise that documentation also mentions …
> Fix backward compatibility with pickles before v22.2.0

- .pre-commit-config.yaml
The previous version is not installable with the latest Poetry anymore but the update in this patch fixes that.
> 🐛 Bump isort to v5.12.0

- .git_archival.txt
- .gitattributes
This patch enables the end-users to succeed installing from GitHub source Git archive URLs, letting `setuptools-scm` calculate the distribution version correctly, including the exports of non-tagged commits [[1]].
[1]: https://github.com/pypa/setuptools_scm#git-archives
So if the current version on PyPI is 23.1.0, the next version is gonna be 23.2.0.
> 📦 Enable support for git archive installs

- .github/workflows/ci.yml
- tox.ini
Instead of using third-party plugins, let's use a few lines of bash to achieve the same thing.
> Determine tox versions on our own

- changelog.d/1092.change.md
- src/attr/_compat.py
This sanity checking code ended up getting decoupled from the old implementation in a18b3957d55c669de56799a9a72ea31febe93ce4 when a new, much simpler method was added. This check can fail spuriously in certain environments where it doesn't even need to be run because the newer approach is used.
This is noticeable when using python scripts compiled by [nuitka](https://github.com/Nuitka/Nuitka). Since next-gen `attrs` uses slots on everything by default, the use of this fixup function is now pervasive, as well.
Here's the simplest reproduction I came up with (tested on Python 3.10.9 and nuitka 1.4)
```python
import attrs
@attrs.define
class Parent:
a: int
def __attrs_post_init__(self):
assert self.__class__ is Child, f"{self.__class__} is not {Child} ({id(self.__class__)}, {id(Child)})" …
```
> compat: move check for closure cellvar update wrapper function

- changelog.d/1099.change.md
- src/attr/__init__.pyi
- src/attr/_compat.py
- src/attr/_funcs.py
- tests/test_annotations.py
Trying to improve `resolve_types`.
> Flesh out resolve_types

- changelog.d/1117.change.md
- src/attr/_funcs.py
- tests/test_funcs.py
this looking ok @ikonst?
Fixes #1109
> Raise a deprecation warning when evolve receives insta as a kw arg

- docs/conf.py
They've deprecated the old syntax.
> Fix intersphinx

- changelog.d/1158.change.md
- docs/extending.md
- src/attr/__init__.pyi
- tests/test_pyright.py
This PR replaces the non-standard `__dataclass_transform__()` in type stubs with `typing.dataclass_transform()`, introduced in [PEP-681](https://peps.python.org/pep-0681/).
The only difference between the two decorators is the naming of one parameter: `field_descriptors=` in `__dataclass_transform__()` is now `field_specifiers=`.
> Switched from __dataclass_transform__() to typing.dataclass_transform()

- changelog.d/1165.change.md
- src/attr/_funcs.py
- tests/test_funcs.py
> Fix TypeError for `asdict(<class with namedtuple>, retain_collection_types=True)`

- .github/workflows/ci.yml
- .gitignore
- changelog.d/1172.change.md
- pyproject.toml
- src/attr/__init__.py
- src/attr/_compat.py
- tests/test_compat.py
> Allow subclassing of AttrsInstance and Protocol at once

- .github/workflows/pypi-package.yml
When updating my fork with upstream, the CI runs `pypi-package.yml`. 
It's good to run the "Build & verify package" job for forks.
But there's no point running the [Test] PyPI upload jobs, because they'll fail because they don't have the credentials set up -- and we wouldn't want to upload from forks anyway.
```
Error: Trusted publishing exchange failure: 
Token request failed: the server refused the request for the following reasons:
* `invalid-publisher`: valid token, but no corresponding publisher (All lookup strategies exhausted)
This generally indicates a trusted publisher configuration error, but could
also indicate an internal error on GitHub or PyPI's part.
```
https://github.com/hugovk/attrs/actions/runs/5916632350/job/16044128992
So let's only attempt to publish for the upstream …
> CI: Only attempt publish for upstream

- src/attr/_next_gen.py
Change "suprising" to "su**r**prising".
> Fix typo in src/attr/_next_gen.py::define's docstring

- changelog.d/1187.change.md
- docs/init.md
- src/attr/_make.py
- tests/test_dunders.py
- tests/test_make.py
Detect if `__attrs_pre_init__` has arguments besides `self` using `inspect.signature`. If so, pass `__attrs_pre_init__` the same arguments that `__init__` (or `__attrs_init__`) expects. This closes #1102.
This is my first contribution to this project, so I would greatly appreciate any feedback.
> Pass args from `__init__` to `__attrs_pre_init__` if requested

- .github/workflows/ci.yml
- pyproject.toml
- tests/test_mypy.yml
- tox.ini
We're running some tests without `strict_optional = False` now, which I think is acceptable (I think that option sucks anyway). It seems to be triggering an issue in typeshed that's too much of a bother to work around.
I've also refactored the dependency tree to be able to use the Mypy version from pyproject.toml in tox, should be better this way, right?
> Bump mypy, fix tests

- .github/workflows/ci.yml
This allows org-hosted projects to start enabling merge queues in the repository settings. With that, GitHub would trigger a separate event against a merge commit derived from merging several pull requests with the target branch.
$sbj. This is preparatory work for the possibility to enable the merge queues feature, but enabling it can be done through the branch protection settings. I'm starting to roll this out across my repos and I like it so far. If you decide to go ahead and enable it, merge this PR first. Also, uncheck the box saying “don't allow queuing failed PRs” ­— it's useful for cases, when several PRs fix CI failures if only merged together.
The first number represents the …
> Enable testing merge queues @ GitHub Actions CI/CD

- tests/test_mypy.yml
- tests/test_pyright.py
Some error messages changed in mypy 1.7.0 and pyright 1.1.335.
Also, test_mypy sometimes fails with xdist (-n auto). A failure I can
reliably reproduce locally is due to changes in type variables numbering.
There may be other issues.
> Fix mypy and pyright tests in CI

- src/attr/_compat.py
- src/attr/_make.py
- tests/test_slots.py
Simple assignment to cell_contents works starting from Python 3.7[1]. This is also the minimum supported version of Python according to pyproject.toml. It follows that we don't need complex work-arounds that were needed in the past.
Also tested on pypy 3.8.
[1] https://bugs.python.org/issue30486
> Remove work-arounds for setting cell_contents

- docs/examples.md
- docs/init.md
* Minor update to the validator/converter docs to more clearly convey information.
* Provide converter example.
This may seem trivial, but some people stop reading after:
> Please note that converters only run on initialization
If the next version is the first …
> Move conditional clause to beginning for validator/converter docs. 

- changelog.d/1221.change.md
- src/attr/_make.py
- tests/test_make.py
- tests/test_slots.py
Address problems raised in https://github.com/python-attrs/attrs/issues/1220 around `cached_property`s in slotted classes:
* class reference remaining causing original class to not be gc'd.
* cached_property functions with class closures not getting updated.
If …
> Slotted cached property reference

- docs/api.rst
I think there is a typo here that links this setters section to the helper `fields` instead of the core API `field`.
> correct reference in Setters section of api.rst

- pyproject.toml
While playing with [*uv*](https://astral.sh/blog/uv), I've run into the problem that apparently the `python_implementation` marker isn't covered by PEP 508: https://peps.python.org/pep-0508/#environment-markers
This fixes it to use the correct `platform_python_implementation`.
> Use PEP 508-compliant marker

- pyproject.toml
`[tool.lint....]` isn't anything 😄 Should be `[tool.ruff.lint]` according to ruff's [docs](https://docs.astral.sh/ruff/configuration/). Hope this doesn't break anything 🤞🏻
> Fix ruff config namespace

- .github/CONTRIBUTING.md
The tox command in CONTRIBUTING.md referred to a tox environment `docs-serve` that no longer exists in the tox.ini.
The tox command in CONTRIBUTING.md was modified to refer to `docs-watch` instead.
> Fixes tox command for watching docs in CONTRIBUTING.md

- docs/init.md
Modifies existing sentence and provides link to an explanation of the common gotcha of mutable default parameters for functions/methods. The change occurs on the "Initialization" page (`init.html`/`init.md`) of the documentation.
The change adds a link is to [this section](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) on [python-guide.org](https://docs.python-guide.org/). I have no connection to [python-guide.org](https://docs.python-guide.org/) — I just like their explanation and would be happy to change it, if you have a better replacement in mind.
The documentation already states that mutable default arguments (probably) don't work as expected and *alludes* to similar gotcha with function/method parameters. I think it could be helpful to provide link to an …
> Modifies sentence and provides link to explanation of mutable defaults gotcha in the documentation

- conftest.py
The deadline is by default 200ms, but this is intended to be useful to the developer and not necessarily recommended for heavily loaded CI systems. Avoid warnings by disabling the deadline completely.
https://github.com/HypothesisWorks/hypothesis/issues/3713 https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.deadline https://lists.openembedded.org/g/openembedded-core/topic/104640034#196437
Fixes:
"""
Unreliable test timings! On an initial run, this test took 268.29ms, which exceeded the deadline of 200.00ms, but on a subsequent run it took 2.63 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.
"""
- There's a ton of footguns waiting if you don't heed this …
> conftest.py: double Hypothesis deadline

- pyproject.toml
- tests/test_funcs.py
`assoc()` no longer raises a deprecation warning since commit 22ae8473fb88d6e585b05c709e81e1a46398a649 but the `with pytest.deprecated_call():` in that test was not removed then (in contrast with other test cases).
Maybe this got unnoticed due to a pytest bug?
In any case, using pytest 8+ (and keeping deprecated_call()) shows that no warning is raised and the test fails.
Removing the upper bound on pytest in dev dependencies as tests now pass with pytest 8.0.
Fix #1233.
Our CI fails if …
> Remove pytest.deprecated_call() in TestAssoc::test_unknown

- src/attr/_compat.py
- tests/test_cmp.py
Compiler in Python 3.13+ strips indents from docstrings so they need to be compared without it for new Pythons.
Tested with 3.13.0a4
Fixes: https://github.com/python-attrs/attrs/issues/1228
> Fix test_ne in test_cmp.py for Python 3.13

- docs/api-attr.rst
`attr.fields_dict` was a link back to itself. The intention, like all the other nearby aliases, was to refer back to the version in `attrs` for the full story.
Omitted for trivial documentation change.
> Fix broken link from attr API reference back to attrs

- changelog.d/1263.deprecation.md
- src/attr/_make.py
- tests/test_make.py
It's pointless in Python 3. define et al never had it.
> Deprecate attr.s's repr_ns

- changelog.d/1264.breaking.md
- src/attr/_funcs.py
- tests/test_funcs.py
As per our deprecation policy.
> evolve: remove support for passing instances per kw

- changelog.d/1268.breaking.md
- src/attr/__init__.py
- tests/test_packaging.py
As per our deprecation policy.
I'll leave the version stuff for a bit longer since it seems to be quite widely used, unfortunately.
> Remove non-version metadata hack

- docs/init.md
Spotted a small typo in `init.md`
`converter=one`
should be
`converter=None`
> Fix small typo in init.md

- bench/test_benchmarks.py
- pyproject.toml
- tests/test_benchmarks.py
- tests/test_functional.py
- tox.ini
Just adding benchmarking to functional tests is a bit too noisy.
> Write specific benchmarks for CodSpeed

- changelog.d/1310.breaking.md
- changelog.d/1310.change.md
- docs/comparison.md
- src/attr/_make.py
- tests/strategies.py
Create the `__eq__` as a chain of ANDed comparisons, instead of a tuple.
On my computer, a class with two attributes now compares almost twice as fast: 141 ns vs 222 ns.
This will introduce a very slight incompatibility which I think is worth it for us (and dataclasses already introduced): attributes that compare equal by identity but not by value (= NaNs) will behave differently.
> Speed up __eq__

- .github/CONTRIBUTING.md
- docs/conf.py
- src/attr/_cmp.py
- src/attr/_funcs.py
- src/attr/_make.py
- src/attr/_next_gen.py
- src/attr/converters.py
- src/attr/filters.py
- src/attr/validators.py
This makes them much more readable while editing.
c.f. https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
This has been a pet peeve of mine lately, since the default style is super crampy and noisy. This takes more space, but is a joy to read.
Rendered:
- https://attrs--1308.org.readthedocs.build/en/1308/api.html
- https://attrs--1308.org.readthedocs.build/en/1308/api-attr.html
> Switch docstrings to Napoleon style

- .github/PULL_REQUEST_TEMPLATE.md
- docs/api-attr.rst
- docs/api.rst
- docs/examples.md
- docs/names.md
- src/attr/_make.py
- src/attr/_next_gen.py
People use and love the new APIs, we've got the Pont Neuf problem, let's invert the API docs.
- `define()`
- https://attrs--1316.org.readthedocs.build/en/1316/api.html#attrs.define
- https://attrs--1316.org.readthedocs.build/en/1316/api-attr.html#attr.s
- `field()`
- https://attrs--1316.org.readthedocs.build/en/1316/api.html#attrs.field
- https://attrs--1316.org.readthedocs.build/en/1316/api-attr.html#attr.ib
> Invert API docs to point from NG to OG

- src/attr/_make.py
I admittedly didn't know, that that class objects always have an `__dict__` with their own attributes (unlike instances).
> Simplify & optimize own attribute detection

- changelog.d/1319.change.md
- src/attr/_make.py
- tests/test_make.py
> Fix crash when __pre_init__, kw_only, and defaults come together

- changelog.d/1320.change.md
- src/attr/validators.py
- tests/test_validators.py
> validators.in_ now transforms certain unhashable options to tuples

- changelog.d/1330.deprecation.md
- src/attr/_make.py
- tests/test_make.py
Given the amount of warnings in the eco-system, make the deprection soft. We won't remove it.
> Only soft-deprecate hash

- changelog.d/1329.change.md
- src/attr/_compat.py
- src/attr/_make.py
- tests/test_3rd_party.py
- tests/test_annotations.py
- tests/test_make.py
- tests/test_slots.py
Essentially switch to PEP 649 / 749 for annotations. Some tests need to be skipped for now, but the rest is working.
Fixes #1326
We probably should open issues for the failing tests, but I'd rather do that only after the first alpha.
> Restore basic functionality on 3.14[sic]

- pyproject.toml
The license definition in `pyproject.toml` is not valid according to the [specification](https://packaging.python.org/en/latest/specifications/pyproject-toml/#license).
As a result, the PyPI API returns `license: null` for this package: https://pypi.org/pypi/attrs/json
This PR fixes this.
So if the current version on PyPI is 22.2.0, the next …
> Fix license definition in project metadata

- .git_archival.txt
Some time ago, it was discovered that Git archives having `ref-names: $Format:%D$` in `.git_archival.txt` may change when references existing in the repository change over time [[1]]. This means that downloading an archive for a commit from an immutable URL may start yielding slightly different results. This hurts the ability of downstreams to source projects from Git archive URLs.
With that in mind, modern `setuptools-scm` advises against having this entry in the `.git_archival.txt` template [[2]]. And this patch implements said recommendation.
[1]: https://github.com/pypa/setuptools_scm/issues/806
[2]: https://setuptools-scm.readthedocs.io/en/latest/usage/#git-archives
> 📦 Make Git archives reproducible

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- changelog.d/1340.breaking.md
- pyproject.toml
- src/attr/__init__.py
- src/attr/__init__.pyi
- src/attr/_compat.py
- src/attr/_make.py
- tests/strategies.py
- tests/test_compat.py
- tests/test_make.py
- tests/test_packaging.py
- tests/test_slots.py
- tox.ini
> Drop Python 3.7

- .github/workflows/ci.yml
happy belated labor day; no public holiday without a self-indulgent curveball by the `actions/(up|down)load` team.
> Fix action/upload's incompatible minor update

- .github/workflows/pypi-package.yml
This patch enables the release workflow to sign the artifacts digitally and attach said signatures to PyPI releases: https://github.com/pypa/gh-action-pypi-publish/pull/236
> Opt into uploading PEP 740 digital publish attestations to PyPI

- .github/workflows/pypi-package.yml
This patch enables the release workflow to sign the artifacts digitally and attach said signatures to PyPI releases: https://github.com/pypa/gh-action-pypi-publish/pull/236.
The bug has been fixed in v1.10.1 and Hugo reported it working elsewhere.
> Opt into uploading PEP 740 digital publish attestations to PyPI once again

- .github/workflows/ci.yml
- tox.ini
We're starting to get permission denied errors when installing with `--system`.
Is it Halloween already or what federal holiday is coming up?
> Stop installing into CI's system

- docs/init.md
It took me a bit to figure out what was meant by the link to the characteristic issue and why there is no such thing as a private argument. Incorporate (my understanding of) the meaning inline and also provide an example of how to work around the _1 syntax error.
Hopefully this new text is more understandable, but I'm happy to rework it further and I won't be sad if you disagree wholly.
> Rephrase the "Private Attributes and Aliases" section

- docs/types.md
This is mentioned very briefly in the API docs for `auto_attrib` but it's not easy to find if you don't already know about `typing.ClassVar`.
> Document how to handle class variables/constants in typed syntax

- src/attr/_next_gen.py
`attrs.define` and `attrs.field` do not actually accept `cmp=` anymore, but the docs still discuss them
Documentation-only fix!
> Remove mention of cmp= from next gen docs

- changelog.d/1365.change.md
- src/attr/_make.py
- tests/test_next_gen.py
> allow __suppress_context__ and __notes__ to be mutated on frozen exceptions

- docs/init.md
Minor documentation fix.
The last example in [post-init](https://www.attrs.org/en/stable/init.html#post-init) was purporting to set an attribute on a frozen instance, but it was in fact using `@define`.
If the next version is the first in the new year, it'll be …
> update frozen post-init example to use frozen

- changelog.d/1372.change.md
- src/attr/converters.py
- tests/test_annotations.py
- tests/test_converters.py
Allow `converter.optional` to take a Converter such as `converter.pipe` as its argument.
Fixes #1348
- (N/A) New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/main/tests/strategies.py).
- (N/A) Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
- (N/A) Updated **documentation** for changed code.
> Allow converter.optional to take a Converter such as converter.pipe as its argument

- src/attr/_make.py
- tests/test_converters.py
Make attrs work with a converter instance that does not evaluate True. Other code spots already do an explicit comparison to None, so do that here as well. Failing to do so on a valid converter instance that is a valid callable but has a `__bool__()` that evaluates to False ends up trying to call `_fmt_converter_call` on that callable rather than on the Converter instance created from it.
- N/A New features have been added to our [Hypothesis testing …
> Use an explicit comparison to None for the converter of a field

- pyproject.toml
PEP 639 has been accepted and is [live](https://discuss.python.org/t/pep-639-round-3-improving-license-clarity-with-better-package-metadata/53020/128).
> Apply PEP 639

- tests/test_pyright.py
- tox.ini
Update the pyright test to match output after pyright 1.1.380, this change was introduced in https://github.com/microsoft/pyright/pull/8896 and the posted comment from github-actions bot in that PR shows the expected diff on attrs.
Fixes #1347.
- (N/A) New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/main/tests/strategies.py).
- (N/A) Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
- (N/A) Updated **documentation** for changed code.
- (N/A) Documentation in `.rst` and `.md` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- (N/A) Changes (and possible deprecations) have news fragments in …
> Fix pyright tests to match expected pyright output after pyright 1.1.380

- .github/workflows/ci.yml
- .readthedocs.yaml
- changelog.d/1383.change.md
- docs/examples.md
- src/attr/__init__.py
- src/attr/_funcs.py
- src/attr/_make.py
- src/attr/_next_gen.py
- tests/test_functional.py
- tox.ini
Fixes #1313
Had to move evolve over due to import cycles and fortunately RTD already supports 3.13.
Since it doesn't overwrite anything, I would wait with adding an own option for if someone actually misses it. 🤷‍♂️
> Implement __replace__ on 3.13

- .github/workflows/ci.yml
- changelog.d/1385.change.md
- pyproject.toml
- src/attr/validators.pyi
- tests/typing_example.py
- tox.ini
> typing: allow union types for instance_of

- tests/test_3rd_party.py
Cloudpickle supports Python 3.14 already.
Fixes: https://github.com/python-attrs/attrs/issues/1397
> Don't expect TestCloudpickleCompat to fail with Python 3.14

- changelog.d/1406.change.md
- src/attr/_make.py
- tests/test_make.py
> Accept valid unicode identifiers as class parameter to make_class

- changelog.d/1410.change.md
- src/attr/_make.py
- tests/test_annotations.py
> Mention what argument has both annotation and type argument

- pyproject.toml
It was introduced in https://github.com/python-attrs/attrs/commit/6bde3618237cdae312e4e7fb006690be2a3ee0f6
> Fix a typo in SPDX comment @ `pyproject.toml`

- src/attr/_make.py
- tests/test_hooks.py
This worked on 25.1.0 but was inadvertently broken by #1401
Fixes #1416
> Cope with `field_transformer` being a generator

- src/attr/_next_gen.py
I found this typo in the docs.
> Use proper formatting for docstring

- changelog.d/1448.change.md
- src/attr/validators.py
- src/attr/validators.pyi
- tests/test_validators.py
- tests/typing_example.py
Fixes #1246
doesn't it @AdrianSosic?
> Make validators optional in deep_mapping

- changelog.d/1461.change.md
- src/attrs/__init__.pyi
- tests/test_pyright.py
Converters passed to `attrs.field()` can currently be specified as `_ConverterType`, `list[_ConverterType]`, or `tuple[_ConverterType]`. The last of these does not mean "tuple of `_ConverterType` instances" as was likely intended; it specifies a tuple with exactly one `_ConverterType` element. The correct form for a `tuple` with any number of instances is `tuple[_ConverterType, ...]`.
This PR corrects the type annotations in `__init__.pyi`, and adds both a `changelog.d` entry, and simple regression test.
I'm quite comfortable using `attrs`, but I'm not familiar with the internals, nor have I contributed to this project before. Please review the proposed changes carefully.
- There's a ton of footguns waiting if you don't heed this warning. You can still go back to your project, create a …
> Fix `attrs.field(converter=...)` type annotations

- bench/test_benchmarks.py
> Add benchmarks for asdict and astuple
