python-attrs/attrs

- CHANGELOG.rst
- src/attr/_funcs.py
- tests/__init__.py
- tests/test_funcs.py
- tox.ini
No docs yet, will come later.
As you see, the change in non-test code is minimal. 
In the test code, I've tried integrating Hypothesis more. We can now generate classes with attributes using Hypothesis. We generate only attributes with defaults, so the classes can be instantiated without prior knowledge of their attributes, and no subclasses.
> Initial dict_factory support for asdict.

- src/attr/_make.py
> ENH: speed up convert.

- CHANGELOG.rst
- src/attr/_make.py
- tests/test_make.py
https://github.com/hynek/attrs/issues/99
> don't overwrite __name__ with __qualname__

- docs/api.rst
- src/attr/_funcs.py
- src/attr/_make.py
- tests/test_funcs.py
This is a continuation of https://github.com/python-attrs/attrs/pull/176.
> Fix evolve (cont)

- docs/examples.rst
> in the form "of", not "on"

- tox.ini
> Use VIRTUALENV_NO_DOWNLOAD in tox

- CHANGELOG.rst
- src/attr/_make.py
- tests/test_make.py
Another regression from the hash fix.
Fixes #203
> Make Factory hashable

- tests/test_make.py
> Fix a typo: suceeds -> succeeds

- docs/api.rst
This should fix #228 – does this meet your expectations @akaptur?
> Add more docs about __attrs_post_init__

- .travis.yml
- CHANGELOG.rst
- CONTRIBUTING.rst
- MANIFEST.in
- PULL_REQUEST_TEMPLATE.md
- changelog.d/102.change
- changelog.d/198.change
- changelog.d/204.change
- changelog.d/226.change
- pyproject.toml
- tox.ini
Fixes #230
No changelog merge conflicts anymore!
Does this make sense @hawkowl ?
> Move changelog to towncrier

- docs/why.rst
I took some time to make our “why not namedtuples?” section more complete and to the point.
I very much welcome feedback and additions.
> Expand notes on namedtuples

- docs/why.rst
> Tweak the English.

- CONTRIBUTING.rst
- README.rst
- docs/api.rst
- docs/examples.rst
- docs/extending.rst
- docs/index.rst
- docs/overview.rst
- docs/why.rst
OK, let’s do this again against master.
Goal is still preparation for narrative docs + being more beginner-friendly.
Rendered version is at http://www.attrs.org/en/narrative-docs/
> Narrative docs

- .travis.yml
Might save us some unfortunate surprises.
> Add Travis environment to check the next 3.6 release

- changelog.d/322.change.rst
- changelog.d/323.change.rst
- src/attr/_make.py
- tests/test_make.py
> Do not delete attributes from class body if these is passed

- changelog.d/331.change.rst
- changelog.d/332.change.rst
- src/attr/_make.py
...and fit into a 32bit integer.
Fixes #331
@mr-nfamous I do not have access to a 32bit Python build – could you verify whether this does what you want? Thank you.
> Make NOTHING's hash vegan

- .travis.yml
Let’s see if this work and how much is broken…
> Add Python 3.7 dev to test matrix

- .github/CONTRIBUTING.rst
Minor edits to typos and style. **No code changes.**
> Typo fixes in contribution guide

- .github/CONTRIBUTING.rst
- .pre-commit-config.yaml
- .travis.yml
- MANIFEST.in
- README.rst
- conftest.py
- docs/conf.py
- pyproject.toml
- setup.cfg
- setup.py
- src/attr/__init__.py
- src/attr/_compat.py
- src/attr/_funcs.py
- src/attr/_make.py
- src/attr/exceptions.py
- src/attr/validators.py
- tests/strategies.py
- tests/test_annotations.py
- tests/test_converters.py
- tests/test_dark_magic.py
- tests/test_dunders.py
- tests/test_filters.py
- tests/test_funcs.py
- tests/test_init_subclass.py
- tests/test_make.py
- tests/test_slots.py
- tests/test_validators.py
- tests/utils.py
- tox.ini
> Fade to Black

- MANIFEST.in
- codecov.yml
We get enough information from the CI status.
> Use codecov.yml to stop comments

- docs/examples.rst
Hi folks, 
Been reading your docs today and spotted a minor typo. Also slightly re-ordered the sentence to scan better.
> Fix minor typo and re-order sentence

- docs/hashing.rst
> Add missing word

- docs/how-does-it-work.rst
"You should avoid $foo, in order to instantiate frozen slotted classes..."
> Fix grammar error in docs

- docs/hashing.rst
> Add warning about subclassing behavior

- docs/init.rst
- docs/types.rst
> Clarify that annotation-only doesn't work w/ decorators

- azure-pipelines.yml
We (and by that I mean "I") forgot to add PyPy(3).
> Add pypy to Azure Pipelines

- docs/init.rst
Thanks for this great project :hugs:
> fix typo in docs

- azure-pipelines.yml
https://developercommunity.visualstudio.com/content/problem/588219/sqlite3-importerror-python-357-and-373.html
Use 3.5 and 3.7 from deadsnakes too.
> [wip] 3.5 and 3.7 are broken on AP and Microsoft doesn't care

- azure-pipelines.yml
> Special case deadsnakes coverage

- azure-pipelines.yml
- setup.py
> Ensure Windows users can install dev versions

- src/attr/_make.py
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
> Fix minor docstring typo

- tests/test_validators.py
Taking up @hynek offer on #600 and keeping the PR simple :)
> Fix simple typo: passses -> passes

- .github/workflows/main.yml
- tox.ini
@ambv is gonna be real mad if we tell him about breakage too late.
> Run CI against 3.9 pre-release

- changelog.d/669.change.rst
- docs/api.rst
- src/attr/__init__.py
- src/attr/__init__.pyi
- src/attr/_next_gen.py
- tests/test_next_gen.py
- tests/typing_example.py
Almost forgot the last part of the NG API puzzle because it doesn't change substantially.
Does this look OK so far?
> Add attr.field

- docs/backward-compatibility.rst
> the twisted backwards compatability policy moved

- MANIFEST.in
- setup.py
- tests/test_mypy.yml
I attempted adding the framework from sqlalchemy-tests but I learned that it involved bring in mypy as a submodule or something weird so I looked elsewhere.  I discovered https://pypi.org/project/pytest-mypy-plugins/ which sounded pretty good and lo and behold it seems to work well.  My hope is to add more tests, possibly all the ones I wrote for mypy, then bring the plugin over here afterwards with tests.  
If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing left to do.  If …
> WIP: Add mypy tests

- changelog.d/732.change.rst
- src/attr/_make.py
- tests/test_dunders.py
> Make NOTHING falsey

- tests/test_mypy.yml
> Fix mypy tests

- src/attr/_compat.py
- src/attr/_make.py
- tests/test_make.py
Fixes #756
Does this look OK to you @avinashmnit30?
> Fix make_class for dynamic generic classes

- .github/workflows/main.yml
Let's see if it's still failing in CI…
> Try 3.10 again

- changelog.d/787.change.rst
- docs/api.rst
- docs/comparison.rst
- src/attr/_cmp.py
> Add narrative docs for #787

- README.rst
> update NASA url

- src/attr/filters.py
- tests/test_filters.py
The code already uses include() and exclude(), so simply tweak the docstrings.
> Avoid whitelist/blacklist terminology

- docs/examples.rst
- docs/hashing.rst
- docs/init.rst
- docs/names.rst
- docs/overview.rst
- docs/python-2.rst
- docs/types.rst
- docs/why.rst
> docs: fix typos and some grammar

- docs/init.rst
> fix type annotation in init.rst example

- src/attr/_cmp.py
- src/attr/_compat.py
- src/attr/_funcs.py
- src/attr/_make.py
- src/attr/filters.py
- tests/test_compat.py
- tests/test_funcs.py
- tests/test_functional.py
- tests/test_validators.py
> Remove various obsolete _compat helpers

- changelog.d/987.change.rst
- src/attrs/__init__.pyi
cf. https://github.com/python-attrs/attrs/issues/987#issuecomment-1206077089
> Re-import AttrsInstance in attrs ns

- .gitignore
- pyproject.toml
- setup.py
- tox.ini
Extracted the 1% nice things we can have from #993
> Switch to 1% static packaging configuration

- setup.py
> Remove universal wheel, python 2 is unsupported

- tox.ini
Also try to see what happens if we run it in older envs.
> Rename typing to mypy since we also have pyright

- README.rst
> Use white logo in dark mode

- changelog.d/1027.change.rst
- src/attr/_cmp.pyi
Does this fix it for you @EpicWink?
Fixes #1026
> Add defaults to cmp_using stubs

- .github/workflows/codeql-analysis.yml
Update `allowed-endpoints` for harden-runner in codeql-analysis.yml
I noticed that `uploads.github.com` was being blocked (example [here](https://github.com/python-attrs/attrs/actions/runs/3293413624)), so am adding to allowed list. 
> Update `allowed-endpoints` in codeql-analysis.yml

- src/attr/__init__.pyi
- src/attr/converters.pyi
- src/attr/setters.pyi
I've tried running ruff over attrs and these issues seem legit.
> Fix minor stub issues

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- .github/workflows/pypi-package.yml
- pyproject.toml
We're already half-way there, so let's finish this.
> Switch to hatch-vcs

- pyproject.toml
- tests/test_mypy.yml
They changed their error messages (and for the better, I think).
> Fix for new Mypy

- docs/init.md
- docs/why.md
I have fixed some typos and rephrased a few sentences in the docs
> Slightly refined documentation while reading it

- .github/workflows/build-docset.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/pypi-package.yml
Sadly, the host names aren't entirely predictable and we're getting spurious CI failures & warnings.
> Drop harden-runner

- src/attr/_funcs.py
- tests/test_funcs.py
c.f. https://github.com/python-attrs/attrs/pull/1117#issuecomment-1494624098
> Stop raising a deprecation warning on assoc

- .github/workflows/ci.yml
ref https://github.com/pytest-dev/pytest/pull/10669
> Remove special-casing of pretend version for pytest

- .readthedocs.yaml
Is there any reason to still build the docs on "old" Ubuntu 20.04?
> Build docs on OS Ubuntu 22.04

- docs/types.md
- tests/dataclass_transform_example.py
- tests/test_pyright.py
- tox.ini
> Fix pyright for 1.1.311

- changelog.d/1141.change.md
- src/attr/__init__.pyi
- tests/typing_example.py
> Fix type annotation for resolve_types()

- .github/workflows/ci.yml
It's a waste of resources to split this up
> Reduce CI matrix

- pyproject.toml
- tests/test_mypy.yml
> Unpin Mypy

- .github/CONTRIBUTING.md
- .github/dependabot.yml
- .github/workflows/ci.yml
- .gitignore
- package-lock.json
- package.json
- tox.ini
Currently my other PR is hanging because the node.js downloads are timing out.
> Stop using nodeenv

- docs/comparison.md
fixes #1191
is this clear enough @DMRobertson?
you can see the rendered docs here: https://attrs--1192.org.readthedocs.build/en/1192/comparison.html
> docs: explain how we compare

- src/attr/validators.py
tiny typo fix for min length validator's error string
> Fix for a tiny typo in `_MinLengthValidator`

- docs/extending.md
Points to the right PEP in the docs.
> Point to data class transform PEP

- docs/examples.md
The example only makes sense if `C2` is the class examined, as that's the one we dynamically created.
> Fixed make_class example.

- .github/workflows/ci.yml
Let's see if it makes a difference.
> Use tox-uv in CI

- .github/workflows/ci.yml
- pyproject.toml
- tests/test_functional.py
- tox.ini
Let's see if we can get a better handle on our performance development.
> Add Codspeed

- pyproject.toml
- tests/dataclass_transform_example.py
- tests/test_pyright.py
- tox.ini
> Unpin/fix Pyright

- .github/workflows/ci.yml
- .github/workflows/codspeed.yml
- .github/workflows/pypi-package.yml
- .pre-commit-config.yaml
- pyproject.toml
- tox.ini
Use the occasion to factor out PyPy jobs which simplifies everything.
> Switch to build-and-inspect-python-package

- .github/workflows/codspeed.yml
It's very slow and very computationally expensive.
No point running it on docs typo changes.
> Only run CodSpeed whenever code changes

- pyproject.toml
- tox.ini
See https://github.com/sphinx-contrib/sphinxcontrib-towncrier/issues/92
> Pin Towncrier

- README.md
- changelog.d/1321.change.md
- docs/examples.md
- docs/init.md
- docs/why.md
- src/attr/_make.py
- src/attr/_next_gen.py
- tests/test_functional.py
Fixes #595
https://attrs--1321.org.readthedocs.build/en/1321/init.html#attrs-and-init-subclass
> Add support for __attrs_init_subclass__

- src/attr/_compat.py
- src/attr/_make.py
- tests/test_converters.py
> Make Converter (including pipe) correctly infer the return type

- .github/PULL_REQUEST_TEMPLATE.md
> Clean up a double "your" in `PULL_REQUEST_TEMPLATE.md`

- docs/glossary.md
> Fix tiny typo in glossary.md

- .github/workflows/ci.yml
- .readthedocs.yaml
- tox.ini
And use uv's downloads. It's from GitHub anyways.
> ci: remove setup-python

- .github/workflows/ci.yml
- pyproject.toml
- tox.ini
- typing-examples/README.md
- typing-examples/baseline_examples.py
- typing-examples/mypy_examples.py
- uv.lock
> Split out Mypy-dependent typing examples, add more type checkers
